ever-co/ever-teams

apps/web/app/hooks/features/useAuthenticateUser.ts

fix: #734 Fixed Blank UI

---

apps/web/app/hooks/features/useTeamInvitations.ts

fix: #734 Close only rejected notification

---

apps/web/app/constants.ts
apps/web/app/helpers/cookies.ts
apps/web/app/hooks/features/usePublicOrganizationTeams.ts
apps/web/app/stores/organization-team.ts
apps/web/pages/api/auth/login.ts
apps/web/pages/api/auth/register.ts
apps/web/pages/team/[teamId]/[profileLink].tsx

fix/#734 Redirect user to main page from public page if already member

---

apps/web/pages/team/[teamId]/[profileLink].tsx

fix: #734 Added refresh for public team page

---

apps/web/pages/api/auth/register.ts
apps/web/pages/api/organization-team/index.ts

fix: #734 Public Team should be selected by default

---

apps/web/app/hooks/features/useTeamTasks.ts

fix: #734 Empty Main input on unassign task

---

apps/web/lib/features/team/user-team-card/index.tsx

fix: #734 Removed Status title in Team page

---

apps/web/lib/features/task/task-displays.tsx

fix: #734 Increased Size of task titles

---

apps/web/lib/components/avatar.tsx

fix: #734 Handled Avatar non-string Image URL

---

apps/web/app/hooks/features/useOrganizationTeams.ts

fix: #734 Refresh token on Remove account

---

apps/web/app/hooks/features/useTaskLabels.ts
apps/web/app/hooks/features/useTaskPriorities.ts
apps/web/app/hooks/features/useTaskSizes.ts
apps/web/app/hooks/features/useTaskStatus.ts
apps/web/app/hooks/features/useTeamTasks.ts

**BEFORE**
[rerender-before.webm](https://user-images.githubusercontent.com/81486442/234761810-0b5f1230-e304-4d74-9236-0561bf55b8f8.webm)
**AFTER**
[rerender-after.webm](https://user-images.githubusercontent.com/81486442/234761853-6370111d-5759-4ed6-ab50-4eca20c8d95c.webm)

fix: #734 Handled re render of Task Status,Size,Priority,Label input

---

apps/web/app/hooks/features/useTimer.ts
apps/web/lib/features/timer/timer.tsx

**Before**
[timer-button-before.webm](https://user-images.githubusercontent.com/81486442/235097409-debfc635-1e04-41b3-a46d-98a7b14d808b.webm)
**After**
[timer-button-after.webm](https://user-images.githubusercontent.com/81486442/235097436-51046bf5-0c4b-447a-8cef-15cae70a8e55.webm)

fix: #734 Timer button disabled unnecessarily

---

apps/web/lib/features/team/user-team-card/task-estimate.tsx

fix/#734 Wrong estimation for current active task

---

apps/web/app/hooks/features/useTeamInvitations.ts

fix: #734 Refresh token on user accept invitation to new Team

---

apps/web/app/hooks/features/useTeamMemberCard.ts

fix: #734 Handled null check

---

apps/web/components/pages/task/details-section/blocks/task-main-info.tsx

When task creator's first name wasn't set(was null) in task description sidebar it was showing "null LastName". Fixed that
https://github.com/ever-co/ever-teams/assets/124465103/988afc31-76cc-480c-81c1-a33f708ef34a

fixed task sidebar creator showing null if user has no firstname

---

apps/web/components/pages/task/title-block/task-title-block.tsx

#1167
Fixed the task title break when has no value
Before:
https://github.com/ever-co/ever-teams/assets/124465103/b4924506-7c9d-4a19-bde2-e63428f994a9
After:
https://github.com/ever-co/ever-teams/assets/124465103/719d9124-3fbb-4795-8057-14c925acc37b

fixed the task title crash when has no value

---

apps/web/components/pages/task/details-section/blocks/task-main-info.tsx
apps/web/lib/features/task/task-input.tsx

Now the input saves title when clicked outside too
https://github.com/ever-co/ever-teams/assets/124465103/700b0573-055e-46a0-9b59-002ca41cb2c4
Also now the remaining days can be seen without setting start date. As we use NOW's date to calculate the remaining days

Fixed Task Card title input saving functionality

---

apps/web/components/pages/task/title-block/task-title-block.tsx
apps/web/components/pages/task/title-block/title-loader.tsx

- Changed loading skeleton's dark theme color to match the project colors
- Made the vertical seperator not visible when data is loading
https://github.com/ever-co/ever-teams/assets/124465103/c6f775cb-247e-45b5-975f-6030c0bdd148

Title Block skeleton dark mode, and vertical seperator hidden when data loading

---

apps/mobile/app/screens/Authenticated/TeamScreen/components/UserHeaderCard.tsx

truncated the name of user if it takes more than 70% of parent width

User name overlap issue

---

apps/mobile/app/components/IssuesModal.tsx

Part of #852
When the issue is "Epic", pressing to open the modal, but it's not visible on phone screen
https://github.com/ever-co/ever-teams/assets/124465103/493bf5ad-7af7-4348-acfe-c6654e854cff

Restricted users to change issue if the current task's type is 'Epic'

---

apps/web/lib/features/task/task-status.tsx

fix: Epic Dropdown UI

---

apps/web/lib/features/task/task-displays.tsx

https://github.com/ever-co/ever-teams/issues/1469

fix: Task Number and Title alignement in Member Tasks page

---

apps/web/app/constants.ts
apps/web/app/helpers/cookies/index.ts
apps/web/app/hooks/features/useOrganizationTeams.ts
apps/web/app/hooks/features/useTeamTasks.ts
apps/web/app/interfaces/IOrganizationTeam.ts
apps/web/app/interfaces/ITask.ts
apps/web/app/services/server/guards/authenticated-guard.ts
apps/web/app/services/server/requests/tasks.ts
apps/web/pages/api/tasks/team.ts

Project-Team mapping

---

apps/web/lib/features/team/invite/user-invite-card.tsx

fix: Invite Card UI alignment

---

apps/web/.env
apps/web/lib/features/integrations/chatwoot/index.tsx
apps/web/pages/_app.tsx

Chatwoot integration

---

apps/web/lib/features/unverified-email.tsx

fix: Verification Code Translation

---

Dockerfile
README.md
apps/web/next.config.js
apps/web/package.json
fly.toml
yarn.lock

- Optimize docker image from 1.2G to 332M uncompressed size
- Use Next standalone output on docker build image
- Fix NextJS "cannot locate sharp dependency package" warning
- Integrate Railway button to deploy
@evereq
We need to deploy this Dockerfile modifications, to make work the Railway template

[DevOps] Build starter for Railway and integrate button to deploy

---

apps/mobile/app/screens/Authenticated/ProfileScreen/components/ListCardItem.tsx

fixed title alignment in profile section cards

---

apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx
apps/mobile/app/screens/Authenticated/TeamScreen/index.tsx

#1742
Users can scroll without navigating to other screens. Also if user has no task, it can't navigate to task screen
https://github.com/ever-co/ever-teams/assets/124465103/d5ec15bd-b824-4184-966e-ebea131484eb

allowing users to navigate only when scrolling is stopped

---

apps/mobile/app/components/CodeField.tsx
apps/mobile/app/components/CodeInput.tsx
apps/mobile/app/screens/LoginScreen/Components/PassCode.tsx
apps/mobile/package.json
apps/mobile/yarn.lock

#1827
In separate PR going to use the created component in all files code input is required
Android:
https://github.com/ever-co/ever-teams/assets/124465103/726dfd09-1a6d-465d-bde3-b7f17f16b6af
iOS: 
https://github.com/ever-co/ever-teams/assets/124465103/e8b4b828-7479-45b9-a19a-cdd8acd08e25

fixed double letter insert and paste issue for android

---

apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx

Conditionally rendering options icon in team member cards

---

apps/mobile/app/screens/Authenticated/SettingScreen/Personal/index.tsx
apps/mobile/app/screens/Authenticated/SettingScreen/Team/index.tsx
apps/mobile/app/screens/Authenticated/SettingScreen/components/UpdateFullNameForm.tsx
apps/mobile/app/screens/Authenticated/SettingScreen/components/UserRemoveAccount.tsx
apps/mobile/app/screens/Authenticated/SettingScreen/index.tsx
apps/mobile/app/screens/Authenticated/TaskLabelScreen/index.tsx
apps/mobile/app/screens/Authenticated/TaskSizeScreen/index.tsx
apps/mobile/app/screens/Authenticated/TaskStatusScreen/index.tsx
apps/mobile/app/screens/Authenticated/TaskVersionScreen/index.tsx

#1907
adjusted zIndex to fix the BlurView taking whole screen, also hiding keyboard when any BottomSheet is closed in Settings
https://github.com/ever-co/ever-teams/assets/124465103/42d61120-d288-427c-81bb-0a5c411c71b4

adjusted zIndex, also closing keyboard when bottom sheets are closing

---

apps/web/components/ui/data-table.tsx
apps/web/components/ui/table.tsx
apps/web/lib/components/pagination.tsx
apps/web/lib/features/task/task-assign-popover.tsx
apps/web/lib/features/task/task-card.tsx
apps/web/lib/features/team-member-cell.tsx
apps/web/lib/layout/auth-layout.tsx
apps/web/lib/settings/danger-zone-personal.tsx
apps/web/lib/settings/danger-zone-team.tsx
apps/web/lib/settings/invitation-setting.tsx
apps/web/lib/settings/left-side-setting-menu.tsx
apps/web/lib/settings/member-setting.tsx
apps/web/lib/settings/personal-setting-form.tsx
apps/web/lib/settings/team-setting-form.tsx
apps/web/lib/settings/version-form.tsx
apps/web/pages/index.tsx
apps/web/pages/settings/personal.tsx
apps/web/pages/settings/team.tsx
apps/web/pages/task/[id].tsx

- Team settings page responsive(danger zone)
- Team settings page responsive(tasks settings)
- Personnal settings page responsive(user form)
- Personnal settings page responsive(danger zone)
- Team settings page responsive(general settings)
- Team settings page responsive(danger zone)

Feat/ make Personnal settings and Team  settings pages responsives 

---

apps/web/components/shared/skeleton/InviteTeamCardSkeleton.tsx
apps/web/middleware.ts

- Routes without lang prefix `(eg: /en/settings -> /settings)`

Fix: remove local lang prefix in route paths

---

apps/web/app/[locale]/page.tsx
apps/web/app/hooks/features/useTaskEstimation.ts
apps/web/app/services/client/api/public-organization-team.ts
apps/web/app/services/server/requests/public-organization-team.ts
apps/web/lib/components/inputs/input.tsx
apps/web/lib/features/auth-user-task-input.tsx
apps/web/lib/features/task/task-estimate.tsx
apps/web/lib/features/team/user-team-card/task-skeleton.tsx
apps/web/lib/features/timer/timer.tsx

* working on home page
* working on home page ui
* fix the auth code issue
* fix the home-page design and responsive
* fix(Home): fixing the homepage design
* fix(Home): fixing the homepage design
* fix(Home): fixing the homepage design
* fix(Home): align and size fix of dropdowns
* fix(Home): align and size fix of dropdowns
* fix(Timer): remove the timer default value
* Update useTaskEstimation.ts
* Update auth-user-task-input.tsx
* fix the hidden value of inputs
* fixed the css of auth input
* fixed the css of auth input
* fix the header of table in home page
* fix(Header): ui of header and added <br/>
* fix(Header): ui of header and added <br/>
* fix(Header): ui of header and added <br/>
* fix(Header): ui of header and added <br/>
* deep scan issues fix
---------

2139 fix home page design and skeleton structure (#2155)

---

apps/web/lib/components/Kanban.tsx
apps/web/lib/components/kanban-card.tsx

Added the 3 dots dropdown in kanban section

2199 feature adding some additional features in kanban

---

apps/web/app/[locale]/kanban/page.tsx
apps/web/app/[locale]/page.tsx
apps/web/lib/components/Kanban.tsx

Fixed the css of kanban 
Added the demo Epic and Label dropdowns for better ui understanding 
Remove the dummy large code of dropdowns and used the shadcn default
Fixed the not working of kanban screen dragging and dropping 
[kanban-height-sizing.webm](https://github.com/ever-co/ever-teams/assets/105014311/91237fcf-2721-4945-831d-9a337ee42d29)

[FIX]: the css of kanban page and added the dropdowns

---

.vscode/settings.json

If users try to search some components in the project they will not find any component due to this change but now it is fixed so that new users will be able to search components
Previously someone copied the code from this URL and pasted in the vscode JSON and not verified folder which is not used in our project.

2439 update search components not found

---

apps/mobile/app/services/interfaces/IOrganizationTeam.ts
apps/web/app/hooks/features/useAuthenticateUser.ts
apps/web/app/interfaces/IOrganizationTeam.ts
apps/web/lib/components/switch.tsx
apps/web/lib/features/task/daily-plan/future-tasks.tsx
apps/web/lib/features/task/task-card.tsx
apps/web/lib/features/task/task-filters.tsx
apps/web/lib/features/user-profile-plans.tsx
apps/web/lib/settings/integration-setting.tsx
apps/web/lib/settings/team-setting-form.tsx

On settings page : 
On a user's profile page :

Member profile page hide some tab options

---

apps/web/app/hooks/features/useTeamTasks.ts
apps/web/app/hooks/features/useTimer.ts
apps/web/components/pages/task/details-section/blocks/task-secondary-info.tsx
apps/web/components/shared/tasks/status-dropdown.tsx
apps/web/lib/features/task/task-item.tsx
apps/web/lib/features/task/task-status.tsx

When Task Status is updated, we sync columns on Kanban view
[screencast-localhost_3030-2024_06_14-12_19_57.webm](https://github.com/ever-co/ever-teams/assets/86450367/79d23be2-ff77-4934-bd11-fc54654b7640)

Fix sync task status kanban

---

apps/web/app/hooks/features/useTimer.ts

Fixing update statistics for task time tricking : 
[x] Timer running : When user clicks on Stop timer, the Today/Total worked time are set to new values
[x] Total daily worked hours for user are updated
[x] During running, After each 1 minute, those values are also updated
[x] All tasks that the user worked home appear on Tab "Worked" on the user profile page
:warning: :warning: :warning: Note : WARNING !!! Before merge this PR, please test other parts of code as I commented some critical first loading conditions. Those tests were the main reason of not updating values after pause timer. It took me some time to detect that.
[screencast-localhost_3030-2024_07_04-17_47_41.webm](https://github.com/ever-co/ever-teams/assets/86450367/b5283b0e-e4eb-407e-a1b6-454018ec5992)

Fix task time tracking issues

---

apps/web/app/api/daily-plan/[id]/remove/route.ts
apps/web/app/api/daily-plan/[id]/route.ts
apps/web/app/hooks/features/useDailyPlan.ts
apps/web/app/interfaces/IDailyPlan.ts
apps/web/app/services/client/api/daily-plan.ts
apps/web/app/services/server/requests/daily-plan.ts
apps/web/app/stores/daily-plan.ts
apps/web/lib/components/modal.tsx
apps/web/lib/features/task/daily-plan/future-tasks.tsx
apps/web/lib/features/task/task-card.tsx
apps/web/lib/features/user-profile-plans.tsx

[Task] 'Daily Plan' | add 'Remove from all plans' option to Action menu #2673
Users should be able to remove plans from a specific day as well as from multiple days
'Remove from all plans'
@evereq 
@Cedric921

[Task] Daily Plan | add 'Remove from all plans' option to Action menu

---

apps/web/lib/features/task/daily-plan/future-tasks.tsx
apps/web/lib/features/user-profile-plans.tsx

For the tab, there is a bit of difference in which Stats is displayed
Planned time (provided by user - planned work time)
Estimate time (total tasks estimates)
Planned tasks (count the number of planned tasks)

[Task]: Daily Plan | tab Future tasks

---

apps/web/lib/components/inputs/auth-code-input.tsx

- User should be able to paste a new value to the input code even if there is a current value. (ability to change the existing value)
[Loom](https://www.loom.com/share/38ae69d094d744a8a16400a5da3a00fc?sid=ee13e7f8-f732-4bee-acc5-3ef459bf3e00)

fixbug: Ability to add 'Code' to Code inputs

---

apps/web/lib/features/task/task-estimate.tsx
apps/web/lib/features/team/user-team-card/task-estimate.tsx

[Loom](https://www.loom.com/share/6ed644fed3ee49ff981e344ed7cc29a6?sid=7ac493ad-d323-420b-ad54-6500a691a7b7)

fixbug: duplicate action icons for estimation hours input

---

.cspell.json
apps/web/lib/features/daily-plan/daily-plan-compare-estimate-modal.tsx
apps/web/lib/features/integrations/livekit/settings-livekit.tsx

- Resolved react/jsx-no-undef error in daily-plan-compare-estimate-modal.tsx by importing ScrollArea.
- Addressed @typescript-eslint/no-empty-interface error in settings-livekit.tsx by disabling the lint rule for the specific line to allow future extensibility.

Fix: Linting issues in settings-livekit and Daily-plan-compare-estima

---

apps/web/app/hooks/features/useAuthTeamTasks.ts
apps/web/lib/features/task/daily-plan/outstanding-all.tsx
apps/web/lib/features/task/daily-plan/task-estimated-count.tsx
apps/web/lib/features/task/task-filters.tsx
apps/web/lib/features/user-profile-plans.tsx

(Daily plan, today tasks, past tasks, future tasks, outstanding)

fix: show number of tasks instead of plans for different tabs

---

apps/web/lib/features/task/daily-plan/past-tasks.tsx
apps/web/lib/features/task/task-card.tsx
apps/web/lib/features/team/user-team-card/task-estimate.tsx
apps/web/lib/features/user-profile-plans.tsx
apps/web/lib/utils.ts

Now, users are not able to edit past plans

fix: user should not edit past plans

---

apps/web/lib/features/task/daily-plan/task-estimated-count.tsx

- Display total estimated time for all tasks in the 'Outstanding' tab (read-only)
- Show the total number of tasks in the 'Outstanding' tab (read-only)

[Fix]: Daily Plan | Total estimated time on Outstanding UI

---

apps/web/lib/features/task/task-filters.tsx
apps/web/lib/features/user-profile-plans.tsx

What I did:
After clicking 'OK' button on the Daily plan suggestion modal:
- Redirect the user to the profile page
- If there are outstanding tasks ⇒ set the current tab to Planned ⇒ Outstanding
- If no outstanding tasks ⇒ set the current tab to Assigned
[Loom](https://www.loom.com/share/a1dbcd283e2c4ed28c3eed35423b9a71?sid=66264e90-8866-45f7-986a-7ef1e5f89aaa)

fix: redirect user to profile page (asigned or outstandings tasks)

---

apps/web/lib/features/integrations/activity-calendar/index.tsx
apps/web/styles/globals.css

Implemented custom month legends using toLocaleString for short month names.

[Feat]: Customize month legend and theme styling 

---

apps/web/app/hooks/useLocalStorageState.ts
apps/web/lib/features/user-profile-plans.tsx

- Added a generic custom hook `useLocalStorageState` that initializes state from localStorage.
- Ensures state is stored and updated in localStorage on change.
- Supports flexible usage with various data types.

[Feat]: Add Generic useLocalStorageState hook for localStorage management

---

apps/web/app/[locale]/auth/passcode/component.tsx

This PR fixes #2896 
Changes made:
- Put the latest selected Workspace on top of the list, in expended mode with the latest team selected
- Collapse other workspaces and let user (expended / collapse) them if needed
[Loom](https://www.loom.com/share/c1e776b55caf41c1a30927e4d8ad7fbe?sid=1ba01446-5d3b-40c8-afc0-0daab54648fa)
[Loom](https://www.loom.com/share/ce0db78d1542417ea2cbb8a5fb0b117c?sid=a5ea46e0-25b8-4548-bb3 …

refactor: improve the workspaces list on login/workspace screen

---

apps/web/lib/features/task/task-estimate.tsx

When the user click on the edit button of the Task estimate component, the focus should be on the first input which has a digit
[Loom](https://www.loom.com/share/27bc7935586c4671acf8225cf7b82ad6?sid=7bfcf2dd-6542-41ca-9ae1-c2387913a1d0)
[Loom](https://www.loom.com/share/a96ceb6ab39445eea66c28e06d93ed39?sid=8ec69390-270e-467f-923f-8580c81daa37)

improvement: focus should be on the first input which has a digit when user click on edit | estimate task

---

apps/web/lib/features/task/task-card.tsx

What I did:
- Add a loading icon when adding the task to tomorrow plan
- Remove the blank space on the Action menu after adding the plan to tomorrow plan
[Loom](https://www.loom.com/share/be49ff7eec0b4afb87b32897a2112296?sid=f20c0f40-583a-4f2d-b3db-e1d631349133)
[Loom](https://www.loom.com/share/8f7f61edf36f4a2397711c28d5353a33?sid=418fa8ef-ee8a-4ace-b6c3-b792d2c5c29f)

fix: Action menu | remove blank space after adding a task to tomorrow plan

---

apps/web/app/hooks/features/useDailyPlan.ts
apps/web/lib/utils.ts

After adding a task to a plan from the outstanding tab, we should remove that task to 'Outstanding' tab
[Loom](https://www.loom.com/share/b7cf8a93d2394f69859b62ccf4ba5e37?sid=7e1f3964-0ace-4f6f-9a5b-694da2f162dc)
[Loom](https://www.loom.com/share/dc373fdd9afd4027843580a69026eedb?sid=6b80d020-8927-4290-81dd-5490558e6ec1)

fix: remove planned task from 'Outstanding' tab

---

apps/web/lib/features/task/task-estimate.tsx
apps/web/lib/features/team/user-team-card/task-estimate.tsx

Reuse one component for all implementations of tasks estimation time (Add, Edit) 

improvement: use the same Task Estimate component on all pages / popups/ Task card

---

apps/web/app/hooks/features/useStartStopTimerHandler.ts
apps/web/lib/features/daily-plan/add-daily-plan-work-hours-modal.tsx
apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx

There was an issue with popups logic in the case where user starts a new day with a plan (could be defined in the past, i.e. yesterday or days before yesterday) 
What I did:
- I make sure to always test the last time a popup was opened (independently)
Additional changes (small):
- Start the timer if users ignore the popup (i.e. User clicks 'X' or cancel/Add later button)

fixbug: SOFT FLOW, popups logic when user added the today plan in the past

---

apps/web/lib/features/task/task-filters.tsx

Redirect the user to "Unassigned" tab if there is no outstanding and assigned tasks in SOFT FLOW if s/he does not have today plan after clicking on "OK" of the Daily plan popup

feat: redirect to 'unassigned' if no oustanding / assigned tasks (SOFT FLOW)

---

.cspell.json
apps/web/app/[locale]/calendar/component.tsx
apps/web/app/[locale]/calendar/page.tsx
apps/web/components/ui/badge.tsx
apps/web/lib/features/integrations/calendar/calendar-component.tsx
apps/web/lib/features/integrations/calendar/helper-calendar.ts
apps/web/lib/features/integrations/calendar/setup-full-calendar.tsx
apps/web/lib/features/integrations/calendar/setup-time-sheet.tsx
apps/web/lib/features/integrations/calendar/table-time-sheet.tsx
apps/web/lib/features/integrations/calendar/time-sheet-filter-popover.tsx
apps/web/lib/features/task/task-filters.tsx

#2805
https://github.com/user-attachments/assets/1e533ae2-2ade-4289-b454-2bd8c20b8331

Feat: refact timesheet

---

apps/web/.env
apps/web/.env.sample
apps/web/components/layout/footer/footer.tsx
apps/web/lib/layout/footer.tsx

remplace hardcodelink in footer componnent

---

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
apps/web/lib/features/task/task-displays.tsx

This PR fixes #2948 
What I did:
- action ( ... ) menu for each task card within the popup
- button [ + ] next to input 'planned time' (the input you can reduce a bit to the left side)

feat: add more elements to the 'Planned tasks' popup

---

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
apps/web/lib/features/task/task-displays.tsx

This PR fixes #2943 
What I did:
- Highlight active task in the "Planned tasks" popup
- Clicking on another task, should be able to select.
- Only one task can be selected
- Scenarios:
1. On the main home page is selected task from Today's plan - then in the planned popup should display that task selected as well by default.
2. On the main home page is selected task NOT from Today's plan - then in the planned popup should display another selected default task (more preferable estimated task, if no estimated than any task for now)
-   [x] I have commented my code, particularly in …

feat:  Implement 'Default' selected task in the planned tasks popup

---

apps/web/app/[locale]/profile/[memberId]/components/UserProfileDetail.tsx
apps/web/app/[locale]/profile/[memberId]/page.tsx
apps/web/app/hooks/features/usePagination.ts
apps/web/components/pages/task/ChildIssueCard.tsx
apps/web/lib/components/lazy-render.tsx
apps/web/lib/features/task/task-input.tsx
apps/web/lib/features/user-profile-tasks.tsx

This PR brings some improvements on tasks rendering with pagination and lazy rendering

Improve Tasks Rendering

---

.cspell.json
apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx

This PR fixes #2961 
What I did:
- User can now remove a task from the today's plan (or all plans) on the 'Planned tasks' popup
[Loom](https://www.loom.com/share/801ce079cc924b32b7a91fe92ef6d58d?sid=bcf31cde-e6a1-4562-acd3-ff4c359410e8)

Planned tasks popup |  add unplan action menu

---

apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx

[UI]: add 'See Plan' option on team member task card menu

---

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx

This PR fixes #3021 
-   [x] Documentation update
[Loom](https://www.loom.com/share/42e112606a374f1da1133e21c6d61f59)

[Improvement] All plans modal | disbale the start working button when the timer is running

---

apps/web/lib/features/daily-plan/all-plans-modal.tsx

refactor: use 'Calendar' / 'Plans' instead of 'Future' / 'Future Plan'

---

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
apps/web/lib/features/daily-plan/all-plans-modal.tsx

The solution is that when the user clicks on "View plan" and there is NO plan for the "Today" and "Tomorrow" tabs, it is now possible to create a plan (add tasks).
On issue #3028

[Improvement] 'See Plan' | ability to add task to Empty plan

---

apps/web/lib/features/daily-plan/all-plans-modal.tsx
apps/web/lib/features/daily-plan/create-daily-plan-form-modal.tsx

Today's date should be a string in calendars

feat: today's date in calenday should look differently

---

apps/web/app/hooks/features/useDailyPlan.ts

Make sure the employeeId is a string in dailyPlans requests

Daily plan requests | employeeId should be a string

---

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
apps/web/lib/features/daily-plan/all-plans-modal.tsx
apps/web/lib/features/team/user-team-card/task-skeleton.tsx
apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx
apps/web/locales/ar.json
apps/web/locales/bg.json
apps/web/locales/de.json
apps/web/locales/en.json
apps/web/locales/es.json
apps/web/locales/fr.json
apps/web/locales/he.json
apps/web/locales/it.json
apps/web/locales/nl.json
apps/web/locales/pl.json
apps/web/locales/pt.json
apps/web/locales/ru.json
apps/web/locales/zh.json

This PR fixes #3028 
[Loom](https://www.loom.com/share/1a5c3023300c4667938f4f6ec47a00b4?sid=a85267c4-7291-4607-a378-2ced31f0c856)

feat: user can add tasks for today / tomorrow plan from 'See plan' modal

---

apps/web/lib/components/accordian.tsx

- Reverse the condition that changes the icon 
- this PR fix the #3080 issue
On #3080 issue
[Screencast from 2024-10-03 07-00-46.webm](https://github.com/user-attachments/assets/ddb499bb-bd8d-47a3-978a-cbef2d21ad71)

[Fix] Settings | Icon direction when sections are collapsed / expended

---

.env.compose
.env.demo.compose
.env.docker
README.md
docker-compose.build.yml
docker-compose.demo.yml
docker-compose.infra.yml
docker-compose.yml

docs: adding Docker & Docker Compose

---

apps/web/core/components/tasks/task-input.tsx

- Fix the task input value on task creation : The full title entered by the user is now saved and persisted without being cut off.
https://github.com/user-attachments/assets/90e63c54-31a1-4144-b9cb-09bc84fc1b00
https://github.com/user-attachments/assets/64231977-b15e-4f56-822b-fac9c652e02c
Please confirm you did the following before asking for review:

[Fix] Fix task input value on task creation
