ever-co/ever-teams

apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx, apps/web/components/pages/task/details-section/blocks/task-progress.tsx, apps/web/components/pages/task/details-section/components/task-row.tsx, apps/web/components/pages/task/task-details-aside.tsx, apps/web/lib/components/inputs/input.tsx, apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/task/task-estimate.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/pages/task/[id].tsx
- removed 'Save' and 'Cancel' buttons
- functioning 'Estimations'
- functioning progress bar
- UI adjustments
https://www.loom.com/share/3375efe1bab74ca9af24ca6a958d17f9
=> Improvements on task details page

apps/web/lib/app/init-state.tsx
=> fix: Invitation list refresh to show in real time

apps/web/app/services/client/api/task-labels.ts, apps/web/app/services/server/requests/task-labels.ts, apps/web/pages/api/tags/pagination.ts
=> fix/ #734 Reduced Label load time

apps/web/lib/features/auth-user-task-input.tsx, apps/web/lib/features/task/task-status.tsx
=> fix: #734 Disable Dropdown on No Task

apps/web/pages/task/[id].tsx
=> fix: #734 disabled timer of it is disabled for user

apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx, apps/web/lib/components/avatar.tsx, apps/web/lib/features/task/task-card.tsx
=> fix/#734 Uneven column size in Task page

apps/web/app/services/server/requests/invite.ts
=> fix: #734 Removed invite list on removing user

apps/web/app/hooks/features/useTeamMemberCard.ts, apps/web/app/interfaces/ITimer.ts, apps/web/pages/api/timer/start.ts
=> fix: #734 Added Organization Team id filter while starting timer

apps/mobile/app/screens/Authenticated/SettingScreen/Personal/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/ChangeUserAvatar.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/PictureSection.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/index.tsx, apps/mobile/app/services/client/queries/user/user.ts, apps/mobile/app/services/hooks/features/useImageAssets.ts, apps/mobile/app/services/hooks/features/useSettings.ts, apps/mobile/app/services/interfaces/IUserData.ts
=> Upload user avatar

apps/web/app/hooks/features/usePublicOrganizationTeams.ts, apps/web/app/hooks/features/useTaskLabels.ts, apps/web/app/hooks/features/useTaskPriorities.ts, apps/web/app/hooks/features/useTaskSizes.ts, apps/web/app/hooks/features/useTaskStatus.ts, apps/web/app/services/server/requests/public-organization-team.ts
=> fix: #734 Public team tasks Status, Size, Label and Priority

apps/web/app/services/server/requests/auth.ts, apps/web/pages/api/auth/send-code.ts
=> fix: Login Email Code link

apps/mobile/app/screens/Authenticated/SettingScreen/Team/TransferOwnership.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/Team/index.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx, apps/mobile/app/services/client/requests/organization-team.ts, apps/mobile/app/services/hooks/useOrganization.ts, apps/mobile/app/services/interfaces/IOrganizationTeam.ts
#382 
https://www.loom.com/share/ecc446c3248a41f59924cea447512c71
=> transfer team ownership

apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/models/team/TeamStore.ts, apps/mobile/app/screens/Authenticated/ProfileScreen/components/ListCardItem.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/index.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/AcceptInviteModal.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/InviteCardItem.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/index.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/logics/useTeamScreenLogic.ts, apps/mobile/app/screens/Authenticated/TimerScreen/index.tsx, apps/mobile/app/services/client/queries/invitation/invitations.ts, apps/mobile/app/services/client/requests/invite.ts, apps/mobile/app/services/hooks/features/useAcceptInviteModal.ts, apps/mobile/app/services/hooks/useOrganization.ts, apps/mobile/app/services/hooks/useTeamInvitation.ts, apps/mobile/app/services/interfaces/IInvite.ts
#643 
https://www.loom.com/share/e605edece6074613a0f7d5cfb57250bc
=> feat: accept and reject invite in app

apps/web/app/hooks/features/useTaskStatistics.ts, apps/web/lib/app/init-state.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/task/task-progress-bar.tsx, apps/web/lib/features/task/task-times.tsx, apps/web/lib/features/timer/timer.tsx, apps/web/lib/features/user-profile-tasks.tsx
=> Task Page Live progress

apps/web/lib/components/avatar.tsx
=> fix: #810 Handled hasOwn undefined error

apps/web/app/hooks/features/useTaskLabels.ts, apps/web/app/hooks/features/useTaskPriorities.ts, apps/web/app/hooks/features/useTaskSizes.ts, apps/web/app/hooks/features/useTaskStatus.ts, apps/web/lib/app/init-state.tsx
=> fix: #734 Added Refresh for Status,Size,Priority,Labels

apps/web/lib/settings/team-setting-form.tsx
**BEFORE**
[team-name-rerender-before.webm](https://user-images.githubusercontent.com/81486442/235345182-d2eaaaa6-8d43-4995-b914-624ff5fe8da9.webm)
**AFTER**
[team-name-rerender-after.webm](https://user-images.githubusercontent.com/81486442/235345190-d8bb3a0f-7f54-4092-86de-6b35f4f391b7.webm)
=> fix: #734 Prevented Team setting details re rendering

apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/task/task-progress-bar.tsx
**BEFORE**
[estimation-before.webm](https://user-images.githubusercontent.com/81486442/235568286-33f5b5bf-d444-4e1c-8d66-425bd6d8e001.webm)
**AFTER**
[estimation-after.webm](https://user-images.githubusercontent.com/81486442/235568316-649c8b64-6d92-4b63-8144-af64924a0780.webm)
=> fix: #734 Updated dynamic estimation for user task card

apps/web/lib/features/team/invite/user-invite-card.tsx
=> fix: Invite Card Timer format

apps/web/app/hooks/features/useTimer.ts, apps/web/app/interfaces/ITask.ts, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/team/user-team-card/task-estimate.tsx, apps/web/pages/profile/[memberId].tsx
=> Re rendering of Member page

apps/web/app/hooks/features/useTaskStatistics.ts, apps/web/lib/features/task/task-progress-bar.tsx
[syn-timer.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/57403689-ddbd-4528-aa25-b1d523f8236a)
=> fix: #726 Sync timer for multiple users

apps/mobile/app/components/CodeInput.tsx, apps/mobile/app/screens/LoginScreen/Components/FillTeamNameForm.tsx, apps/mobile/app/screens/LoginScreen/Components/PassCode.tsx, apps/mobile/ios/Podfile.lock
#749 
https://www.loom.com/share/badf500f62c049d7a29048844ebe5d3e
=> update login flow

apps/web/app/hooks/features/useAuthTeamTasks.ts
=> fix:#734 Worked tab tasks filtered as per current user

apps/web/lib/features/task/task-progress-bar.tsx
=> fix: #850 Progressbar NaN issue handled

apps/web/lib/features/task/task-times.tsx, apps/web/lib/settings/profile-avatar.tsx
=> fix: Total Timer and Avatar logic updated

apps/web/app/hooks/features/useOrganizationTeams.ts
[team-dropdown-mismatch-after.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/14730ffd-2f0b-4e4b-a136-02d5add0101c)
=> fix: #862 Team Dropdown listing updated

apps/web/app/hooks/features/useTaskStatistics.ts, apps/web/pages/auth/passcode.tsx, apps/web/pages/auth/team.tsx
**BEFORE**
[ui-alignment-before.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/2688cfb4-252a-42e5-b043-7ac8757f7c8f)
**AFTER**
[ui-alignment-after.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/e84e3cab-63fb-4fc4-87bc-140d1d166b8c)
=> Fix/#786 UI alignment

apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/task/task-assign-button.tsx, apps/web/lib/features/task/task-card.tsx
=> fix: #870 Added Assign task button on Unassigned tab of Task Profile page

apps/web/lib/features/auth-user-task-input.tsx
=> fix: #328 Updated default task assignment logic

apps/web/lib/layout/auth-layout.tsx
=> fix: Auth UI

apps/web/app/hooks/features/useEmployee.ts, apps/web/app/interfaces/IEmployee.ts, apps/web/app/interfaces/hooks.ts, apps/web/app/services/client/api/employee.ts, apps/web/app/services/client/api/index.ts, apps/web/app/services/server/requests/employee.ts, apps/web/app/stores/employee.ts, apps/web/lib/components/auto-complete-dropdown.tsx, apps/web/lib/features/team/invite/invite-email-dropdown.tsx, apps/web/lib/features/team/invite/invite-email-item.tsx, apps/web/lib/features/team/invite/invite-form-modal.tsx, apps/web/package.json, apps/web/pages/api/employee/working.ts
[demo-invite-updated-ui.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/e364d409-7cc7-4023-902c-29fb3a41dd4a)
=> feat: #330 Updated Invite input to Auto complete

apps/web/lib/components/toggler.tsx, apps/web/lib/layout/auth-layout.tsx
**BEFORE**
[footer-flicker-before.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/5ac250ab-6765-40c9-8782-7031ea804eda)
**AFTER**
[footer-flicker-after.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/c6573779-9a2b-461c-b46a-c5a88d4be947)
=> fix: Solved footer UI flickering issue

apps/mobile/app/screens/Authenticated/ProfileScreen/components/FilterPopup.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskFilter.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskLabelFilter.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskPriorityFilter.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskSizeFilter.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskStatusFilter.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/UserProfileTasks.tsx, apps/mobile/app/services/hooks/features/useTaskFilters.ts
#819 
https://www.loom.com/share/60ceb822ac0d45c4a30d444f0f2ebbce
=> Fix filter issue

apps/web/lib/components/pagination.tsx, apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx, apps/web/lib/settings/invitation-setting.tsx, apps/web/lib/settings/invitation-table.tsx, apps/web/lib/settings/member-setting.tsx, apps/web/lib/settings/member-table.tsx, apps/web/lib/settings/table-action-popover.tsx
**BEFORE**
**AFTER**
**Video**
[delete-member-from-team-settings.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/5638e411-d432-4b1e-96e9-ee53e7b72bc3)
=> Enabled Delete member feature from members list, fixed dark mode UI

apps/web/lib/i18n/en.ts, apps/web/lib/settings/confirmation-modal.tsx, apps/web/lib/settings/invitation-setting.tsx, apps/web/lib/settings/invitation-table.tsx, apps/web/lib/settings/member-setting.tsx, apps/web/lib/settings/member-table.tsx, apps/web/lib/settings/table-action-popover.tsx
=> Added delete confirmation, fixed minor issues

apps/web/app/hooks/features/usePagination.ts, apps/web/app/hooks/features/useTeamMember.ts, apps/web/app/interfaces/IOrganizationTeam.ts, apps/web/app/interfaces/hooks.ts, apps/web/app/stores/organization-team.ts, apps/web/app/stores/permission.ts, apps/web/components/pages/404/index.tsx, apps/web/lib/components/divider.tsx, apps/web/lib/components/pagination.tsx, apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/permission/permission-dropdown.tsx, apps/web/lib/features/permission/permission-item.tsx, apps/web/lib/features/task/task-item.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/confirmation-modal.tsx, apps/web/lib/settings/invitation-table-status.tsx, apps/web/lib/settings/invitation-table.tsx, apps/web/lib/settings/member-table.tsx, apps/web/lib/settings/permission-popover.tsx, apps/web/lib/settings/table-action-popover.tsx, apps/web/lib/settings/team-setting-form.tsx, apps/web/pages/404.tsx, apps/web/pages/permissions/index.tsx
=> Member Actions, Permission Popup

apps/web/app/hooks/features/useRequestToJoinTeam.ts, apps/web/app/hooks/features/useRoles.ts, apps/web/app/interfaces/IEmployee.ts, apps/web/app/services/client/api/index.ts, apps/web/app/services/client/api/roles.ts, apps/web/app/services/server/requests/roles.ts, apps/web/app/stores/index.ts, apps/web/app/stores/roles.ts, apps/web/lib/features/permission/permission-dropdown.tsx, apps/web/lib/features/permission/permission-item.tsx, apps/web/lib/settings/member-table.tsx, apps/web/pages/api/auth/verify/resend-link.ts, apps/web/pages/api/roles/[id].ts, apps/web/pages/api/roles/index.ts
[role-permission.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/919747f1-4628-4fa4-a56a-94a1ab859e11)
=> Added Roles CRUD for Permission page

apps/web/app/hooks/features/useRequestToJoinTeam.ts, apps/web/app/interfaces/IRequestToJoin.ts, apps/web/app/services/client/api/request-to-join-team.ts, apps/web/app/services/server/requests/request-to-join-team.ts, apps/web/lib/settings/invitation-table-status.tsx, apps/web/lib/settings/invitation-table.tsx, apps/web/lib/settings/member-setting.tsx, apps/web/pages/api/organization-team-join/[id]/[action].ts
[gt-accept-join-request.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/d6e7bc04-beb9-4082-88b7-6cadf900d565)
[gt-reject-join-request.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/1bccf929-eebc-48dd-9140-231eeb3024b4)
=> feat: Integrated API to accept/reject Team join request

apps/mobile/app/components/CodeInput.tsx, apps/mobile/app/config/config.dev.ts, apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/Authenticated/SettingScreen/components/BottomSheetContent.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/ConfirmEmailPopup.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/ContactInfoForm.tsx, apps/mobile/app/services/client/requests/auth.ts, apps/mobile/app/services/client/requests/email-reset.ts, apps/mobile/app/services/hooks/features/useUser.ts, apps/mobile/app/theme/colors.ts
=> Improve change email flow

apps/web/app/hooks/features/useTaskVersion.ts, apps/web/app/hooks/index.ts, apps/web/app/interfaces/ITaskVersion.ts, apps/web/app/interfaces/index.ts, apps/web/app/services/client/api/index.ts, apps/web/app/services/client/api/task-version.ts, apps/web/app/services/server/requests/task-version.ts, apps/web/app/stores/index.ts, apps/web/app/stores/task-version.ts, apps/web/lib/app/init-state.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/issues-settings.tsx, apps/web/lib/settings/version-form.tsx, apps/web/pages/api/task-versions/[id].ts, apps/web/pages/api/task-versions/index.tsx
[gt-versions.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/8eeb50e4-cd7b-4c9b-b444-5304ffeb1e5e)
=> feat: #902 Added Team Version

apps/web/app/hooks/features/useTaskRelatedIssueType.ts, apps/web/app/hooks/index.ts, apps/web/app/interfaces/ITaskRelatedIssueType.ts, apps/web/app/interfaces/index.ts, apps/web/app/services/client/api/index.ts, apps/web/app/services/client/api/task-related-issue-type.ts, apps/web/app/services/server/requests/index.ts, apps/web/app/services/server/requests/task-related-issue-type.ts, apps/web/app/stores/index.ts, apps/web/app/stores/task-related-issue-type.ts, apps/web/lib/app/init-state.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/issues-settings.tsx, apps/web/lib/settings/related-issue-type-form.tsx, apps/web/pages/api/task-related-issue-types/[id].ts, apps/web/pages/api/task-related-issue-types/index.ts
[gt-related-issue.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/68e0d4b7-44b7-454a-ba62-407a41ccf6b7)
=> feat: #902 Added related issue type

apps/mobile/app/components/HamburgerMenu.tsx, apps/mobile/app/components/Screen.tsx, apps/mobile/app/components/TeamDropdown/DropDown.tsx, apps/mobile/app/models/task/TaskStore.ts, apps/mobile/app/models/team/TeamStore.ts, apps/mobile/app/navigators/AppNavigator.tsx, apps/mobile/app/navigators/AuthenticatedNavigator.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/Personal/UserAvatar.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/Personal/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/Team/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/SectionTab.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/index.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/index.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/logics/useTeamScreenLogic.ts, apps/mobile/app/screens/Authenticated/TimerScreen/index.tsx, apps/mobile/app/services/hooks/useOrganization.ts
=> fix: remove user from all teams

apps/mobile/app/components/HomeHeader.tsx, apps/mobile/app/components/TaskPriority.tsx, apps/mobile/app/components/TaskSize.tsx, apps/mobile/app/components/TaskStatus.tsx, apps/mobile/app/config/config.dev.ts, apps/mobile/app/screens/Authenticated/SettingScreen/Personal/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/Team/QuitTeam.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/BottomSheetContent.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/ChangeUserAvatar.tsx, apps/mobile/app/services/client/queries/user/user.ts, apps/mobile/app/services/hooks/features/useAuthentificateUser.ts, apps/mobile/app/services/hooks/features/useSettings.ts, apps/mobile/app/services/hooks/features/useTaskLabels.ts, apps/mobile/app/services/hooks/features/useTaskPriority.ts, apps/mobile/app/services/hooks/features/useTaskSizes.ts, apps/mobile/app/services/hooks/features/useTaskStatus.ts, apps/mobile/app/services/hooks/useOrganization.ts
#966 
https://www.loom.com/share/6fe606eb002344ba9f27ce4f925a6127?sid=7ad21172-e359-4b8a-80a4-12ffc27a1b69
=> fix: BUG | Delete account from another device crashes the app

apps/web/app/hooks/features/useAuthTeamTasks.ts, apps/web/app/hooks/features/useOTRefreshInterval.ts, apps/web/app/hooks/features/usePagination.ts, apps/web/app/hooks/features/usePublicOrganizationTeams.ts, apps/web/app/hooks/features/useRefreshInterval.ts, apps/web/app/hooks/features/useTaskInput.ts, apps/web/app/hooks/features/useTimer.ts, apps/web/components/pages/task/description-block/task-description-block.tsx, apps/web/lib/components/auto-complete-dropdown.tsx, apps/web/lib/components/avatar.tsx, apps/web/lib/components/pagination.tsx, apps/web/lib/components/svgs/icons.tsx, apps/web/lib/components/themes-popup.tsx, apps/web/lib/features/team/invite/invite-email-dropdown.tsx, apps/web/lib/features/team/invite/invite-email-item.tsx, apps/web/lib/features/team/invite/invite-form-modal.tsx, apps/web/pages/task/[id].tsx
* https://github.com/ever-co/ever-gauzy-teams/issues/987
* Fixed terminal warnings
* Fix not well placed description field placeholder - task page
* Hide (Comment) UI uncompleted features on task page
- Child issues
- Related issues 
- Proof of completion
- Activities
=> Minor improvements 

apps/web/app/hooks/features/useTimer.ts, apps/web/app/interfaces/ITimer.ts, apps/web/app/services/client/api/timer.ts, apps/web/app/services/server/requests/timer.ts, apps/web/lib/features/timer/timer.tsx, apps/web/pages/api/timer/start.ts, apps/web/pages/api/timer/status.ts, apps/web/pages/api/timer/stop.ts, apps/web/pages/api/timer/sync.ts, apps/web/pages/api/timer/toggle.ts
[timer-sync.webm](https://github.com/ever-co/ever-gauzy-teams/assets/81486442/2a5c25f0-fd0a-43f8-a4df-6d8d9c4f32d5)
**DESKTOP**:
**BROWSER_EXTENSION**
**UPWORK**
**HUBSTAFF**
**MOBILE**
=> feat: #995 Added Icon for currently running timer

apps/web/components/pages/task/details-section/blocks/task-secondary-info.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/lib/features/team/invite/invite-email-dropdown.tsx, apps/web/lib/settings/issues-settings.tsx, apps/web/lib/settings/related-issue-type-form.tsx, apps/web/lib/settings/task-labels-form.tsx, apps/web/lib/settings/task-priorities-form.tsx, apps/web/lib/settings/task-sizes-form.tsx, apps/web/lib/settings/task-statuses-form.tsx, apps/web/lib/settings/version-form.tsx, apps/web/pages/task/[id].tsx
- fixed #520 
User can create new status in the dropdown menu
=> #520 task page side panel status block

apps/web/lib/features/timer/timer.tsx
=> Added tooltip to indicate currently running timer source

apps/web/lib/features/timer/timer.tsx
=> fix: BROWSER_EXTENSION text to BROWSER EXTENSION

apps/web/components/pages/task/description-block/tool-button.tsx
Fixed the build error by adding tool-button back
=> fixed the build error by adding the deleted file back

apps/web/app/helpers/date.ts, apps/web/app/hooks/useModal.ts, apps/web/components/pages/task/CompletionBlock.tsx, apps/web/components/pages/task/IssueCard.tsx, apps/web/components/pages/task/description-block/task-description-editor.tsx, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx, apps/web/components/pages/task/details-section/blocks/task-secondary-info.tsx, apps/web/lib/features/index.ts, apps/web/lib/features/task/task-item.tsx, apps/web/lib/features/task/task-status-modal.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/task-labels-form.tsx, apps/web/lib/settings/task-priorities-form.tsx, apps/web/lib/settings/task-sizes-form.tsx, apps/web/lib/settings/task-statuses-form.tsx, apps/web/lib/settings/version-form.tsx, apps/web/pages/task/[id].tsx, apps/web/styles/globals.css
- Fix #936
- Basic style for DateTime picker (Still need more improvements)
=> 936 task page create new task popup task issue

apps/web/lib/components/svgs/ever-teams-logo.tsx, apps/web/lib/components/svgs/index.ts, apps/web/lib/layout/auth-layout.tsx, apps/web/lib/layout/navbar.tsx
=> Logo - gauzy teams to ever teams

apps/web/lib/features/unverified-email.tsx, apps/web/lib/i18n/en.ts
[gt-fix-verification-text.webm](https://github.com/ever-co/ever-teams/assets/81486442/f31a61a5-d348-42e3-99e8-a58811683363)
=> fix: #1028 Updated Verification code text

apps/web/app/interfaces/ITask.ts, apps/web/components/pages/task/TaskProperties.tsx, apps/web/components/pages/task/description-block/editor-footer.tsx, apps/web/components/pages/task/description-block/task-description-editor.tsx, apps/web/lib/i18n/en.ts, apps/web/pages/task/[id].tsx
#510 Created a component that shows when the task is created, updated and resolved. 
The resolved date-time string currently is null, however functionality is added, when from DB date comes it will be reflected to the DOM
Before:
After:
=> created the task-properties bellows the task sidebar

apps/web/components/pages/task/description-block/editor-toolbar.tsx
Created copy effect, copy button can be presseed once per sec
https://github.com/ever-co/ever-teams/assets/124465103/f9325234-d217-4810-8599-eb1c57a57415
=> created effect when copy button is pressed

apps/web/lib/components/index.ts, apps/web/lib/components/no-data.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/invitation-setting.tsx, apps/web/lib/settings/member-setting.tsx
=> Feat/#1053 no data UI

apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx, apps/web/components/pages/task/details-section/blocks/task-progress.tsx
=> made the chevron icon visible in dark theme

apps/web/app/hooks/features/useTeamTasks.ts, apps/web/app/hooks/features/useUserProfilePage.ts, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx, apps/web/components/pages/task/details-section/components/profile-info.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/task/task-item.tsx, apps/web/lib/features/team/team-item.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx, apps/web/lib/features/user-nav-menu.tsx, apps/web/pages/api/timer/timesheet/statistics-tasks.ts, apps/web/pages/profile/[memberId].tsx
* WIP: Avatar fix
* WIP: Avatar fix
* fix: User Nav Avatar
* fix: Task Page Avatar
* fix: Member Task page, statistics and Task Item
* fix: nav menu and team item
=> Fix/#1116 app crash due to image url (#1118)

apps/web/app/interfaces/ITask.ts, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx
=> fix: #1086 Added Reset Date for start and due date

apps/web/components/pages/task/IssueCard.tsx, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx, apps/web/components/pages/task/details-section/blocks/task-publicity.tsx, apps/web/components/pages/task/title-block/task-title-block.tsx, apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/task/task-displays.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/pages/index.tsx, apps/web/pages/profile/[memberId].tsx, apps/web/pages/settings/personal.tsx, apps/web/pages/settings/team.tsx, apps/web/pages/task/[id].tsx
- Fix #1091
- Fix #1069
- Fix #1108
- Fix #1106
- Fix #1103
- Fix #1102
- Fix #1094
- Fix #1108
- Fix #1089
- Fix #1088
=> 1107 long task title is not looking good

apps/web/components/pages/task/title-block/task-title-block.tsx
=> fix: Reduce size of Task Title

apps/web/components/pages/task/TaskProperties.tsx
=> aligned the task property labels

apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/user-nav-menu.tsx, apps/web/pages/index.tsx
=> fix: Home icon, replaces with Team icon

apps/web/lib/components/inputs/auth-code-input.tsx, apps/web/pages/auth/passcode.tsx
[Fix-Login-Code.webm](https://github.com/ever-co/ever-teams/assets/81486442/c3844f46-dad5-4d40-b88a-a98d71c4c6ef)
=> fix: #1151 Fixed code pasting in email input

apps/web/lib/features/timer/timer.tsx, apps/web/styles/globals.css
[Ever-Teams-Time-Color.webm](https://github.com/ever-co/ever-teams/assets/81486442/c3aedb93-0566-436c-9bce-edbc51fad3a6)
=> Timer Color/Icon animation updated

apps/web/components/pages/task/description-block/editor-footer.tsx, apps/web/components/pages/task/description-block/task-description-editor.tsx
#1183 
https://github.com/ever-co/ever-teams/assets/124465103/be48eb38-0603-409d-949f-7063ad5856fc
=> Bug/When task description is in edit mode, shouldn't change the description's size

apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/task/task-status.tsx
Added circle icon when no value is selected in the dropdowns. Added to all dropdowns as in my opinion it looks more consistent
=> added the circle icon to the dropdowns when they have no value

apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/task/task-all-status-type.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/lib/layout/auth-layout.tsx, apps/web/pages/auth/passcode.tsx
=> Feat/Icon to remove currently selected Task(#1174)

apps/web/components/pages/task/title-block/task-title-block.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/timer/timer.tsx, apps/web/pages/index.tsx
#1211
Also removed labels above user cards on screens smaller than sm
[screen-capture (2).webm](https://github.com/ever-co/ever-teams/assets/124465103/7e7bfbc1-41cf-4c64-b37e-975ca3be9cd2)
=> Made the task input go full width over 2xl screens

apps/web/components/pages/task/TaskProperties.tsx, apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx, apps/web/components/pages/task/details-section/blocks/task-progress.tsx, apps/web/components/pages/task/details-section/blocks/task-publicity.tsx, apps/web/components/pages/task/details-section/blocks/task-secondary-info.tsx, apps/web/components/pages/task/details-section/components/profile-info-with-time.tsx, apps/web/components/pages/task/details-section/components/profile-info.tsx, apps/web/components/pages/task/task-details-aside.tsx, apps/web/lib/features/task/task-labels.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/pages/task/[id].tsx, apps/web/styles/globals.css
[Ever-Teams-Before.webm](https://github.com/ever-co/ever-teams/assets/81486442/3c95280f-1a4d-4e62-b257-a4586f2a015d)
[Ever-Teams-After.webm](https://github.com/ever-co/ever-teams/assets/81486442/a53a6d32-0d6d-44fa-a5bd-9cd215fef0bf)
=> Fix/task details sidebar UI alignments

apps/web/components/pages/task/description-block/editor-components/CheckListElement.tsx, apps/web/lib/i18n/en.ts, apps/web/tailwind.config.js
=> Bug/task description description UI

apps/web/components/pages/task/details-section/blocks/task-publicity.tsx
For instant ui reaction used state, also debounce function
https://github.com/ever-co/ever-teams/assets/124465103/322dd45d-dcda-4fc1-8f3c-5f51bba7e2c2
=> added functionality to instantly change task publicity ui

apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx, apps/web/components/pages/task/details-section/blocks/task-progress.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/task/task-displays.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/task/task-issue.tsx, apps/web/lib/features/task/task-item.tsx, apps/web/lib/features/task/task-linked-issue.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx, apps/web/lib/features/user-profile-tasks.tsx
=> Bug/task type badge UI

apps/web/components/pages/task/IssueCard.tsx, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx
* Removed unused code
* fix: Card Overlapping
* fix: Card menu alignment, minor fix
=> Fix/refactoring (#1232)

apps/web/components/layout/header/request-to-join-modal.tsx, apps/web/lib/components/auto-complete-dropdown.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx
=> Fix/public page UI

apps/web/components/pages/main/no-team.tsx, apps/web/lib/features/auth-user-task-input.tsx, apps/web/lib/features/task/task-all-status-type.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/team/team-item.tsx, apps/web/lib/features/team/teams-dropdown.tsx, apps/web/lib/features/user-nav-menu.tsx, apps/web/lib/settings/icon-items.tsx, apps/web/pages/auth/passcode.tsx, apps/web/pages/auth/team.tsx
[Ever-Teams-Dropdown.webm](https://github.com/ever-co/ever-teams/assets/81486442/9271fad3-bfcc-4db9-8288-de766756a5d7)
=> Minor fixes

apps/web/components/pages/task/title-block/task-title-block.tsx
#1243 
https://github.com/ever-co/ever-teams/assets/124465103/c7e51ea1-37f8-4bee-8123-23d3cec573a5
=> Task Title on Enter save, also padding

apps/web/app/hooks/features/useTimer.ts, apps/web/app/interfaces/ITask.ts, apps/web/lib/features/task/task-default-status.tsx
https://github.com/ever-co/ever-teams/assets/124465103/ec5849f1-5f40-46a2-b155-99c88479273d
=> Fixed on Timer start status becomes null

apps/web/lib/components/svgs/icons.tsx, apps/web/lib/components/tooltip.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx, apps/web/styles/globals.css
=> Updated Manager icon in user card

apps/web/app/hooks/features/useTaskInput.ts, apps/web/lib/components/color-picker.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx, apps/web/lib/settings/icon-popover.tsx
#1265 
[Ever-Teams.webm](https://github.com/ever-co/ever-teams/assets/81486442/bae4d229-c2ec-4b53-991a-6713d0e7d36e)
=> fix: #1265 Edit task title, minor UI fixes

apps/web/components/pages/task/IssueCard.tsx
#1267 
[Ever-Teams.webm](https://github.com/ever-co/ever-teams/assets/81486442/a249a73e-92b8-42ed-b529-6486282a515f)
=> fix:#1267 Updated Child issue popup list

apps/web/app/hooks/features/useTimer.ts, apps/web/app/interfaces/ITimer.ts, apps/web/app/services/server/requests/timer.ts, apps/web/lib/features/timer/timer.tsx, apps/web/pages/api/timer/start.ts
=> feat: Added TEAMS source as a default source

apps/mobile/app/helpers/name-format.ts, apps/mobile/app/screens/Authenticated/TaskPrioritiesScreen/components/PriorityItem.tsx, apps/mobile/app/screens/Authenticated/TaskStatusScreen/components/StatusItem.tsx
=> Fixed the task status page error, and added format name helper

apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx
=> Current user won't have option to make himself manager

apps/mobile/app/screens/Authenticated/SettingScreen/Team/index.tsx
#960 
https://github.com/ever-co/ever-teams/assets/124465103/ef0f02fc-7700-4a74-a38d-9e4e2bc78ded
=> Made the team settings labels dynamic

apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/Authenticated/SettingScreen/components/ContactInfoForm.tsx, apps/mobile/package.json, apps/mobile/yarn.lock
https://github.com/ever-co/ever-teams/assets/124465103/09a58138-2753-42ab-b6b4-51bb57d975bb
=> Stopped updating email and phone values when in edit mode

apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/Authenticated/SettingScreen/components/ContactInfoForm.tsx, apps/mobile/package.json, apps/mobile/yarn.lock
* stopped updating email and phone values when in edit mode
* added editMode in useEffect dependencies
* removed comma
* added a library for email validation
* used better validator for the email
* removed the debounce function
* updated the not valid email and phone notify messages
=> Stopped updating email and phone values when in edit mode (#1284)

apps/web/lib/components/inputs/input.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/personal-setting-form.tsx
* added email and phone validation functionality
* added text to the translation file
=> Bug/email validation when changing (#1288)

apps/web/components/pages/task/details-section/blocks/task-estimations-info.tsx, apps/web/lib/features/task/task-input.tsx
=> Tiny Fixes

apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx
https://github.com/ever-co/ever-teams/assets/124465103/8f4162d5-52fa-4868-b2d9-15a4d305780b
=> Added the function to unassign member from the given task in Teams Section

apps/web/lib/features/team/user-team-card/user-info.tsx, apps/web/pages/profile/[memberId].tsx
=> fix: User time tracking on another device

apps/web/components/pages/task/details-section/blocks/task-progress.tsx, apps/web/lib/layout/navbar.tsx
https://github.com/ever-co/ever-teams/issues/1310
https://github.com/ever-co/ever-teams/assets/81486442/b9697ac5-1ba5-4314-82ff-829b46eabb3e
=> Showing Team dropdown on relevant pages only

apps/mobile/app/screens/Authenticated/SettingScreen/components/SwitchTimeTracking.tsx
Before:
https://github.com/ever-co/ever-teams/assets/124465103/36c6cd48-9161-422f-80a4-9cdc57bcaf7a
After:
https://github.com/ever-co/ever-teams/assets/124465103/b3802872-6d01-4682-a324-2eb1259127df
=> Added null checker to fix the error that appears when removing team

apps/web/components/pages/task/details-section/blocks/task-secondary-info.tsx, apps/web/lib/features/task/task-status.tsx
https://github.com/ever-co/ever-teams/issues/1318
https://github.com/ever-co/ever-teams/assets/81486442/4583bf27-7898-4ac8-813c-ac2cd9111ead
=> fix: #1318 Dynamic values of Epic Dropdown

apps/web/app/hooks/features/usePublicOrganizationTeams.ts, apps/web/app/services/client/api/public-organization-team.ts, apps/web/app/services/server/requests/public-organization-team.ts, apps/web/lib/features/task/task-input.tsx, apps/web/pages/api/public/team/[profileLink]/[teamId].ts, apps/web/pages/team/[teamId]/[profileLink].tsx
https://github.com/ever-co/ever-teams/issues/1325
---
https://github.com/ever-co/ever-teams/assets/81486442/1d8f9084-a31f-4e0e-85f1-ee062535b037
=> fix: #1325 Public Team Page Crash

apps/web/components/layout/header/request-to-join-modal.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/pages/team/[teamId]/[profileLink].tsx
* fix: Minor issues
* fix: Minor background issue
=> fix: Minor issues (#1330)

apps/web/middleware.ts, apps/web/pages/auth/passcode.tsx
=> fix: cookie reset issue, fixed login UI

apps/web/lib/components/color-picker.tsx, apps/web/lib/components/emoji-picker.tsx, apps/web/lib/components/switch.tsx, apps/web/lib/settings/team-setting-form.tsx, apps/web/lib/settings/team-size-popover.tsx
=> Toggle fixed

apps/web/app/hooks/auth/useAuthenticationPasscode.ts, apps/web/lib/i18n/en.ts
https://github.com/ever-co/ever-teams/issues/1352
https://github.com/ever-co/ever-teams/assets/81486442/ccd7d258-a62a-4e26-b50b-70de4b873caa
=> fix: #1352 Handle workspaced not found case

apps/web/app/helpers/img-title.ts, apps/web/lib/settings/invitation-setting.tsx, apps/web/pages/auth/passcode.tsx
=> fix: Organization Team Join Crash, login UI fix

apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/Authenticated/TeamScreen/components/InviteCardItem.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/index.tsx
#1364
https://github.com/ever-co/ever-teams/assets/124465103/5ca92d48-1a06-46f2-92ed-e136e3be6fb9
Same labels in Web:
=> User Card options labels menu fix - Mobile

apps/web/components/pages/task/details-section/blocks/task-secondary-info.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/task/task-item.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx, apps/web/lib/features/timer/timer-button.tsx, apps/web/lib/features/timer/timer-status.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/settings/team-size-popover.tsx, apps/web/pages/profile/[memberId].tsx, apps/web/pages/task/[id].tsx
=> fix: Filter UI

apps/web/lib/features/task/task-labels.tsx, apps/web/lib/features/task/task-status.tsx
https://github.com/ever-co/ever-teams/assets/81486442/38477358-34ca-4222-9f1e-c32926918414
=> fix: Updated label dropdown

apps/web/app/hooks/features/useTaskStatus.ts, apps/web/lib/settings/related-issue-type-form.tsx, apps/web/lib/settings/task-labels-form.tsx, apps/web/lib/settings/task-priorities-form.tsx, apps/web/lib/settings/task-sizes-form.tsx, apps/web/lib/settings/task-statuses-form.tsx, apps/web/lib/settings/version-form.tsx
=> fix: Unnesessary API calling on Edit

apps/web/lib/features/task/task-status.tsx
https://github.com/ever-co/ever-teams/assets/81486442/f20a4051-9f5f-4b7b-9d6a-1c0b676f5e7f
=> fix: Build issue

apps/web/lib/features/task/task-status.tsx
https://github.com/ever-co/ever-teams/assets/81486442/e5e44278-35d0-4147-836d-53aed2ec6dc8
=> fix: Task Filter issue

apps/mobile/app/components/CreateTeamModal.tsx, apps/mobile/app/components/HamburgerMenu.tsx, apps/mobile/app/components/TaskLabelPopup.tsx, apps/mobile/app/screens/Authenticated/TimerScreen/components/TaskLabels.tsx, apps/mobile/app/screens/Authenticated/TimerScreen/components/TimerTaskSection.tsx, apps/mobile/app/services/client/api/auth/signin.ts, apps/mobile/app/services/hooks/features/useAuthenticationTeam.ts, apps/mobile/app/services/hooks/features/useTeamTasks.ts
#1359
- Made all tags visible, scrollable
- Added functionality to create new labels
https://github.com/ever-co/ever-teams/assets/124465103/d8e160af-82d8-48f5-a902-eb23d072c8a3
=> Timer section label tags

apps/web/lib/features/team/team-item.tsx, apps/web/lib/settings/team-avatar.tsx, apps/web/pages/settings/team.tsx
https://github.com/ever-co/ever-teams/assets/81486442/8c607540-4686-4215-8b41-7e1d8251e113
=> fix: Dynamic Team Color

apps/mobile/app/components/AllTaskStatuses.tsx, apps/mobile/app/components/TaskPriority.tsx, apps/mobile/app/components/TaskSize.tsx, apps/mobile/app/components/TaskStatus.tsx, apps/mobile/app/components/TaskStatusPopup.tsx, apps/mobile/app/services/client/queries/task/task-priority.ts, apps/mobile/app/services/client/queries/task/task-sizes.ts, apps/mobile/app/services/client/queries/task/task-status.ts, apps/mobile/app/services/client/requests/task-priority.ts, apps/mobile/app/services/client/requests/task-size.ts, apps/mobile/app/services/client/requests/task-status.ts, apps/mobile/app/services/hooks/features/useTaskLabels.ts, apps/mobile/app/services/hooks/features/useTaskPriority.ts, apps/mobile/app/services/hooks/features/useTaskSizes.ts, apps/mobile/app/services/hooks/features/useTaskStatus.ts, apps/mobile/app/services/interfaces/ITaskLabel.ts, apps/mobile/app/services/interfaces/ITaskPriority.ts, apps/mobile/app/services/interfaces/ITaskSize.ts, apps/mobile/app/services/interfaces/ITaskStatus.ts
* fixed task statuses not sync between web and mobile
* modified task priority api to to sync mobile and web priorities
* fixed task size fetch url in order to sync with web
* fixed task label create api fetch
* fixed the logic of setting current task's status so it matches with Web app's logic at all times
* fixed the task size, to be synced with Web
* fixed the task sizes, when set to be displayed in both Web and Mobile
=> Bug/task statuses not sync (#1394)

apps/web/app/interfaces/ITimer.ts, apps/web/components/ui/toast.tsx, apps/web/lib/features/team/team-item.tsx, apps/web/lib/features/team/teams-dropdown.tsx, apps/web/lib/i18n/en.ts
https://github.com/ever-co/ever-teams/issues/1402
https://github.com/ever-co/ever-teams/assets/81486442/f34ef3d5-26e8-47d7-a3af-abc512103d64
=> fix: #1402 Automatically Stop timer when it started on GT Web and user try to change team

apps/web/lib/features/team/user-team-card/user-info.tsx, apps/web/lib/features/user-nav-menu.tsx, apps/web/pages/profile/[memberId].tsx
https://github.com/ever-co/ever-teams/issues/1409
=> fix: Current Timer Status

apps/web/lib/components/color-picker.tsx, apps/web/lib/components/emoji-picker.tsx, apps/web/lib/settings/team-setting-form.tsx, apps/web/lib/settings/team-size-popover.tsx
=> fix: Disabled fields for Member users

apps/web/lib/components/svgs/icons.tsx, apps/web/lib/i18n/en.ts, apps/web/pages/index.tsx
`Before`
https://github.com/ever-co/ever-teams/assets/81486442/bc71d333-3a63-447d-b3fd-5794906cbb05
`After`
https://github.com/ever-co/ever-teams/assets/81486442/a93b999d-418c-4cb3-bd3f-d601b51c117e
=> fix: Breadcrumb aligment issue, refactored collab UI

apps/web/components/pages/task/description-block/editor-components/CheckListElement.tsx
#1421
https://github.com/ever-co/ever-teams/assets/124465103/500f8a6c-a953-4f00-9d72-5cca39b54ede
=> fixed line margin issue when first element of the editor is checklist

apps/web/lib/features/task/task-filters.tsx
https://github.com/ever-co/ever-teams/issues/1429
https://github.com/ever-co/ever-teams/assets/81486442/a56f1119-0e4f-4b01-a5b9-9b9ba984a2a1
=> fix:#1429 Member Tasks page Label filter is not working

apps/mobile/app/screens/Authenticated/SettingScreen/index.tsx
#382
https://github.com/ever-co/ever-teams/assets/124465103/02101c1a-00a3-4150-b63e-68851989dd66
=> Fixed the issue where danger zones weren't pressable

apps/web/lib/settings/member-table.tsx, apps/web/lib/settings/table-action-popover.tsx
=> fix: #1435 Member UI alignement fixed for Safari

apps/web/app/hooks/features/useTimer.ts, apps/web/app/services/server/requests/organization-team.ts, apps/web/lib/features/task/task-all-status-type.tsx
https://github.com/ever-co/ever-teams/issues/1436
https://github.com/ever-co/ever-teams/assets/81486442/f1a514c1-5245-4ce0-b281-81e9b06f3d4b
=> fix: #1436 Member Task Sync between multiple users

apps/web/lib/features/task/task-input.tsx
`BEFORE`
https://github.com/ever-co/ever-teams/assets/81486442/c1a93509-6bc8-4f6e-8aa2-1da613256b74
`AFTER`
https://github.com/ever-co/ever-teams/assets/81486442/f53ac3cb-7d17-4106-8a92-2fe4dfcde5b9
=> fix: #1436 Started showing Issue Type Dropdown everytime while creating new Issue

apps/web/lib/components/inputs/auth-code-input.tsx
#1465
https://github.com/ever-co/ever-teams/assets/124465103/5afa72fe-4ed9-4c88-bc26-9bb6a19f96aa
=> added functionality to make the code input's value capitalized

apps/web/lib/settings/member-table.tsx
https://github.com/ever-co/ever-teams/issues/1476
https://github.com/ever-co/ever-teams/assets/81486442/12d9e830-f70d-4fd5-bd74-dc4f6da700e3
=> fix: #1476 Alignment resize issue on edit name

apps/web/lib/features/auth-user-task-input.tsx, apps/web/lib/features/task/task-status.tsx
=> fix: Task Input Dropdown text view

apps/mobile/app/components/svgs/icons.tsx, apps/mobile/app/navigators/AuthenticatedNavigator.tsx
#1521
Updated the bottom navigator icons. Changed some of the icons to SVG. The library weren't able to read other, for that reason couldn't use SVGs there
https://github.com/ever-co/ever-teams/assets/124465103/af1ec83e-7ce1-4aa6-ad1c-fe68dc84b228
=> updated bottom navigator's icons

apps/mobile/app/components/CodeInput.tsx, apps/mobile/app/screens/LoginScreen/Components/PassCode.tsx
#1536
Before:
After:
https://github.com/ever-co/ever-teams/assets/124465103/401ee698-9cbf-45b2-a8e6-0fbeea2cfab8
=> Updated the input field appearance when latest logout was in dark theme

apps/mobile/app/components/LabelIcon.tsx, apps/mobile/app/components/PriorityIcon.tsx, apps/mobile/app/components/SizeIcon.tsx
#1545
https://github.com/ever-co/ever-teams/assets/124465103/862b6bab-5dc8-4272-90d1-39c460c39f94
Before:
=> Formatted names in popups

apps/mobile/app/components/TimerCard.tsx
#1537
https://github.com/ever-co/ever-teams/assets/124465103/8e44f662-63a9-4e36-8c1e-3ed929a2bfd8
=> Fixed the progress bar to show value

apps/web/lib/features/integrations/boards/AppMainMenu.tsx, apps/web/lib/features/integrations/boards/index.tsx
I removed the Excalidraw links
=> Improve board menu

apps/web/app/utils/index.ts, apps/web/app/utils/queue.ts, apps/web/app/utils/wait.ts, apps/web/lib/features/task/task-labels.tsx, apps/web/lib/features/task/task-status.tsx
- #1355
https://www.loom.com/share/56a3c6a279bf4f3089e24954b3a9bcdf
=> Fix/#1355 Task Status randomly not saving updated value

apps/web/app/hooks/index.ts, apps/web/app/hooks/useDetectOS.ts, apps/web/app/hooks/useHotkeys.ts, apps/web/lib/components/keyboard-shortcuts.tsx, apps/web/lib/components/svgs/icons.tsx, apps/web/lib/features/task/task-assign-popover.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/timer/timer.tsx, apps/web/lib/i18n/en.ts, apps/web/lib/layout/navbar.tsx, apps/web/package.json, yarn.lock
**`Mac`**
https://github.com/ever-co/ever-teams/assets/81486442/d014993c-4ce3-42ec-be70-c70eb15156b9
**`Windows`**
https://github.com/ever-co/ever-teams/assets/124465103/ebdb90c9-f6fe-4828-b1de-4015acbe1a39
=> Shortcut keys implementations

apps/web/app/hooks/features/useOrganizationProjects.ts, apps/web/app/hooks/index.ts, apps/web/app/interfaces/IOrganizationTeam.ts, apps/web/app/interfaces/IProject.ts, apps/web/app/services/client/api/index.ts, apps/web/app/services/client/api/organization-projects.ts, apps/web/app/services/server/requests/index.ts, apps/web/app/services/server/requests/organization-projects.ts, apps/web/lib/settings/integration-setting.tsx, apps/web/pages/api/organization-projects/setting/[id].ts
https://github.com/ever-co/ever-teams/assets/81486442/e03f5115-4bac-4728-9ebd-181e4dc786ac
=> feat: Added Mapping between Repo-Organization Project

apps/web/lib/features/timer/timer-status.tsx
=> fix: User Deactivated Case for Timer

apps/web/lib/features/team/user-team-card/index.tsx
`Before`
https://github.com/ever-co/ever-teams/assets/81486442/f442e701-83b7-455a-a6eb-0f233c48fc12
`After`
https://github.com/ever-co/ever-teams/assets/81486442/3a603b78-5b07-4f4d-b378-88eacbd4b9c4
=> fix: Updated Task Card Size

apps/mobile/app/screens/Authenticated/ProfileScreen/components/ListCardItem.tsx
Now:
https://github.com/ever-co/ever-teams/assets/124465103/4077fb3b-4afd-42cc-85fe-6fd9924a187e
Before:
https://github.com/ever-co/ever-teams/assets/124465103/59a98e0a-b6e9-4b2e-ba67-a63708ac1107
=> changed the event listener to be activated on normal press

apps/mobile/app/components/TeamDropdown/DropDownSection.tsx
=> fixed the timer screen teams dropdown non active teams positioning

apps/mobile/app/components/HamburgerMenu.tsx, apps/mobile/app/screens/Authenticated/TimerScreen/components/ComboBox.tsx, apps/mobile/app/screens/Authenticated/TimerScreen/components/IndividualTask.tsx
#1603
Fixed the issue: when scrolling the set active task function triggering
Now:
https://github.com/ever-co/ever-teams/assets/124465103/badfb465-48a1-4e45-8e22-95cc62146a81
Before:
https://github.com/ever-co/ever-teams/assets/124465103/3e47338f-3512-4fa5-9b36-5018e23aa79f
=> when user is scrolling no longer active task is set

apps/mobile/app/components/AllTaskStatuses.tsx, apps/mobile/app/components/TaskLabels.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/ListCardItem.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/UserProfileTasks.tsx
#1600
Now:
https://github.com/ever-co/ever-teams/assets/124465103/594d6a79-8a51-480e-8677-9e0f6b0f3f43
Before:
=> border indicating task running is removed from last 24 hours section

README.md
- Fix #1607
https://www.loom.com/share/aa53220ac0aa4c66a352716bb16190f2
=> One-click deployment to Vercel

apps/web/app/hooks/integrations/useGitHubIntegration.ts, apps/web/app/services/server/requests/integrations/github.ts, apps/web/lib/settings/integration-setting.tsx, apps/web/pages/api/integration/github/repository/sync.ts
https://github.com/ever-co/ever-teams/assets/81486442/7e768b3f-a1be-406b-8e2f-89fef8e99829
=> fix: Github Repo selection

apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team-members-table-view.tsx, apps/web/lib/features/team-members.tsx, apps/web/lib/i18n/en.ts, apps/web/pages/index.tsx
=> Reset card UI

apps/mobile/android/app/build.gradle
@evereq I changed the code version, otherwise play store will reject it.
=> tiny changes

apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team-members.tsx
**BEFORE**
https://github.com/ever-co/ever-teams/assets/81486442/c9e710fb-932e-40f6-ab22-bb2beb2ebcfd
**AFTER**
https://github.com/ever-co/ever-teams/assets/81486442/76f4260e-4d72-4c9e-bb29-123ddbc4b21c
=> fix: Unneccessary Loader

.gitignore, README.md, apps/web/package.json, netlify.toml, railway.json, yarn.lock
* https://github.com/ever-co/ever-teams/issues/1644
=> [DevOps] Deploy to Netlify

apps/mobile/app/screens/Authenticated/ProfileScreen/components/ProfileHeader.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx
#1703 and #1713
Added team logo and name, also fixed the crash issue from previous issue
=> added team logo and name in profile screen, also fixed the issue in 1703

apps/mobile/app/components/TaskEpicPopup.tsx
#1718
Current:
Before:
https://user-images.githubusercontent.com/81486442/280996864-baeed1e2-6394-43dd-b3ce-d81aa33730ba.png
=> fixed the epic popup alignment

Dockerfile, Procfile, README.md, app.json, heroku.yml
- Fix #1695
Demo: https://ever-teams-ea46aef91916.herokuapp.com/auth/team
=> [DevOps] Deploy to Heroku button

apps/web/components/pages/task/description-block/task-description-editor.tsx
#1774
Current:
https://github.com/ever-co/ever-teams/assets/124465103/6cae35c5-91f7-4b81-9a30-e496168e4a29
Before:
https://github.com/ever-co/ever-teams/assets/124465103/a501a891-a254-4b0c-9d9f-5671753045da
=> fixed the key so re-renders description for each task

apps/web/components/pages/task/details-section/blocks/task-main-info.tsx
#1781
https://github.com/ever-co/ever-teams/assets/124465103/67f4541a-00eb-4191-9c1e-7e6222a6588b
=> limited height and added scroll to manage assignees

apps/mobile/app/screens/Authenticated/SettingScreen/components/TimezonePopup.tsx, apps/web/lib/components/dropdown.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/settings/timezone-dropdown.tsx
#1796
https://github.com/ever-co/ever-teams/assets/124465103/358e650d-d360-49f0-ba44-5a42a0fa3246
https://github.com/ever-co/ever-teams/assets/124465103/5d0179eb-3b5e-4702-9133-794e55a2e3ac
https://github.com/ever-co/ever-teams/assets/124465103/9050ee9e-056e-40e6-9291-0dcf54556c33
=> added debounced search to web and mobile

apps/mobile/app.json, apps/mobile/ios/GauzyTeams/Info.plist, apps/mobile/ios/Podfile.lock, apps/mobile/package.json, apps/mobile/yarn.lock
**Fix build errors for ios & android** 
- There is no deobfuscation file associated with this App Bundle
- iOS Compliance
=> fix build errors for ios and android

apps/mobile/app/screens/Authenticated/ProfileScreen/components/ListCardItem.tsx
#1794
Current:
https://github.com/ever-co/ever-teams/assets/124465103/8f113c55-93a0-47d5-93b5-a9366e08d9e8
Before:
https://github.com/ever-co/ever-teams/assets/124465103/6bd0284a-8047-47ec-b0f3-6eeb5196d971
=> fixed the card resizing when pressing options button

apps/mobile/app/components/CodeInput.tsx, apps/mobile/app/components/TextField.tsx, apps/mobile/app/components/svgs/icons.tsx, apps/mobile/app/models/AuthenticationStore.ts, apps/mobile/app/screens/LoginScreen/Components/EmailVerificationForm.tsx, apps/mobile/app/screens/LoginScreen/Components/FillTeamNameForm.tsx, apps/mobile/app/screens/LoginScreen/Components/FillUserInfoForm.tsx, apps/mobile/app/screens/LoginScreen/Components/LoginBottom.tsx, apps/mobile/app/screens/LoginScreen/Components/PassCode.tsx, apps/mobile/app/screens/LoginScreen/Components/UserTenants.tsx, apps/mobile/app/screens/LoginScreen/index.tsx
#1801
Kept the background color of the upper part of the screen same in both themes. Let me know if we should change that @evereq ?
https://github.com/ever-co/ever-teams/assets/124465103/f1d5677d-864a-48ca-9e27-4dba92c958ab
=> Added dark theme to Login/Register screen

apps/web/lib/settings/timezone-dropdown.tsx
- React Infinite Rendering timezone dropdown
=> Fix/React Infinite Rendering

apps/mobile/app/components/TeamDropdown/DropDown.tsx, apps/mobile/app/components/TeamDropdown/DropDownSection.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/ProfileHeader.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskFilter.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/AcceptInviteModal.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/UserHeaderCard.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/index.tsx
=> added nullish operators to fix errors

apps/mobile/app/screens/Authenticated/ProfileScreen/components/ListCardItem.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/TaskTitleDisplay.tsx
#1795
https://github.com/ever-co/ever-teams/assets/124465103/6ccb6a77-6f78-49bf-b1bb-ca62113ff65a
=> added navigation when task title pressed in profile screen

apps/mobile/app/screens/Authenticated/MembersSettingsScreen/index.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskLabelScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskPrioritiesScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskSizeScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskStatusScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskVersionScreen/index.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/index.tsx, apps/mobile/app/screens/Authenticated/TimerScreen/index.tsx
=> added status bar to screens

apps/mobile/android/app/build.gradle, apps/mobile/eas.json, apps/mobile/ios/GauzyTeams/Info.plist
https://docs.expo.dev/build-reference/app-versions/
=> chore: bump version and attempt on auto-increment

apps/mobile/app/navigators/AuthenticatedNavigator.tsx
=> aligned the navigation icons vertically in android devices

apps/mobile/app/components/Task/DetailsBlock/blocks/TaskMainInfo.tsx, apps/mobile/app/components/TaskLabels.tsx, apps/mobile/app/screens/Authenticated/ProfileScreen/components/UserProfileTasks.tsx
#1849
Components in Task Screen, and Profile Screen were causing the error:
https://github.com/ever-co/ever-teams/assets/124465103/0c415c83-408e-41b5-8222-da99bc8650a6
The error:
https://github.com/ever-co/ever-teams/assets/124465103/23056833-a501-4375-b1aa-d67cac2b825c
=> fixed java errors with style types

apps/mobile/app/screens/Authenticated/TimerScreen/components/TimerTaskSection.tsx
#1851
Now on Android:
Before on Android:
=> truncated text in android and aligned with task number

apps/web/app/hooks/features/useTimer.ts, apps/web/app/hooks/useQuery.ts
https://github.com/ever-co/ever-teams/assets/81486442/d5cbbad1-6a4c-4a27-b99e-52250c8b5810
=> fix: #1867 Improved API performance issue for timer status API

apps/web/components/ui/svgs/priority-icon.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/lib/features/team-members-kanban-view.tsx, apps/web/pages/kanban/index.tsx
=> make column color dynamic

apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/LoginScreen/Components/PassCode.tsx
#1903
Samsung S8+:
iPhone 13 Pro Max:
Pixel 3a:
Pixel 7Pro:
=> displaying the email address to which code is sent when login

apps/mobile/app/components/TimerCard.tsx
#1911
Pixel 3a:
https://github.com/ever-co/ever-teams/assets/124465103/7499f5f2-b536-44c4-8eb7-78f3403ff6b7
Pixel 7 Pro:
https://github.com/ever-co/ever-teams/assets/124465103/25627905-742a-4471-9c5f-1ea42818b96e
Samsung S8+:
https://github.com/ever-co/ever-teams/assets/124465103/e8a9fafb-e999-48e3-9b62-a1c09765d8fe
iPhone 13Pro Max:
https://github.com/ever-co/ever-teams/assets/124465103/95f64cde-44ee-4986-a22c-de4329caa6d3
Before:
https://github.com/ever-co/ever-teams/assets/124465103/8e8ce2e9-6b26-4b54-934d-f42261a359fb
=> fixed the timer width

apps/mobile/app/helpers/get-timer-status.ts, apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/fr.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/Authenticated/SettingScreen/Team/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/SwitchTeamPublicity.tsx, apps/mobile/app/screens/Authenticated/TeamScreen/components/ListCardItem.tsx
https://github.com/ever-co/ever-teams/assets/124465103/1723bba3-f2df-4209-be7e-be9a88c9d5a7
=> added team publicity switcher, and changed the timer status code order

apps/mobile/app/i18n/ar.ts, apps/mobile/app/i18n/bg.ts, apps/mobile/app/i18n/en.ts, apps/mobile/app/i18n/es.ts, apps/mobile/app/i18n/he.ts, apps/mobile/app/i18n/ko.ts, apps/mobile/app/i18n/ru.ts, apps/mobile/app/screens/Authenticated/SettingScreen/Team/index.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/SingleInfo.tsx
Added the same conditions as the Web App
=> added conditionally disabling same as web app to team danger zone

apps/web/app/hooks/auth/useAuthenticationPasscode.ts, apps/web/app/hooks/features/useAuthTeamTasks.ts, apps/web/app/services/client/api/organization-team.ts, apps/web/pages/api/auth/login.ts
https://github.com/ever-co/ever-teams/issues/1921
=> fix: Multiple time invitation accept with same link

apps/web/pages/auth/passcode.tsx
https://github.com/ever-co/ever-teams/issues/1925
=> fix: #1925 Workspace Login when no team available

apps/web/app/hooks/features/useTeamTasks.ts, apps/web/lib/features/task/task-displays.tsx
=> fix: Minor Task Page Child Issues

apps/web/app/hooks/features/useTimer.ts, apps/web/lib/features/task/task-displays.tsx, apps/web/lib/features/timer/timer.tsx
https://github.com/ever-co/ever-teams/issues/1968
=> fix: #1968 Timer Button Enable condition

apps/web/components/ui/data-table.tsx, apps/web/lib/features/team-members-block-view.tsx, apps/web/lib/features/team-members.tsx, apps/web/lib/features/team/user-team-table/user-team-table-header.tsx, apps/web/pages/index.tsx
- Texts when filters data is empty
- Table Header fixed
=> Fix/table show text mesage after loading skeletons in Block View of team issues

apps/web/app/constants.ts, apps/web/components/ui/svgs/kanaban.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/pages/index.tsx
* update:add kanban to issuesview
* feat:add kanban icon
* update:add tooltip to view icons
* update:add timer to inprogress
* chore:remove unused values
* update:fix issues with scroll
=> Update/view mode icon (#1992)

apps/web/lib/features/task/task-item.tsx, apps/web/lib/features/team-member-cell.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-table/user-team-table-header.tsx, apps/web/lib/settings/invitation-table.tsx, apps/web/lib/settings/member-table.tsx, apps/web/pages/index.tsx, apps/web/pages/settings/personal.tsx, apps/web/pages/settings/team.tsx
if table has large columns it scroll horizontally.
=> Feat/tablet make tables (tasks and team members) responsive on tablets devices

apps/web/lib/layout/auth-layout.tsx, apps/web/lib/layout/footer.tsx
=> fix: Footer and Auth Layout Translation

apps/web/lib/components/dropdown.tsx, apps/web/lib/features/team/teams-dropdown.tsx
https://www.loom.com/share/5587dd39fbd1495b85dd9f061fe2f981?sid=ffd58e8d-94c1-4660-9da2-6c1989a3f38a
=> fix:resolve scroll issues

.cspell.json, apps/mobile/app/services/client/requests/organization-team.ts, apps/web/app/hooks/features/useOrganizatioTeamsEmployee.ts, apps/web/app/interfaces/IOrganizationEmployeeTeam.ts, apps/web/app/interfaces/IOrganizationTeam.ts, apps/web/app/services/client/api/organization-team.ts, apps/web/app/services/server/requests/organization-team.ts, apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team-members.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/pages/api/organization-team/employee/[id].ts
[screen-recorder-thu-dec-21-2023-23-31-07.webm](https://github.com/ever-co/ever-teams/assets/83704005/8b54c03c-9bfd-4551-b038-0e676a67e517)
=> Feat/cardOrder:  make cards element (of list view) draggable 

apps/web/lib/components/kanban-card.tsx
https://github.com/ever-co/ever-teams/issues/2032
=> fix: Sometime Timer automatically starts when user goes to Kanban page

apps/web/lib/features/user-profile-tasks.tsx
- when User has one task ( working task only)
- When User worked last 24hours and not working now
- When User is working now  and worked in last 24hours
=> refact: improve logic to display tasks on profile page

apps/web/lib/settings/version-form.tsx
=> fix: Version UI

apps/web/components/shared/skeleton/InviteTeamCardSkeleton.tsx, apps/web/components/shared/skeleton/Skeleton.tsx, apps/web/components/shared/skeleton/UserTeamCardSkeleton.tsx, apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx, apps/web/styles/globals.css
- Make skeleton less white in Dark Theme
- remove scroll bar on Task infos of Team Member
[screen-recorder-tue-jan-02-2024-16-41-48.webm](https://github.com/ever-co/ever-teams/assets/83704005/41f8eb3d-0e3a-48e8-ac2a-e38470c3f8dd)
=> Fix:  skeleton less color in Dark Theme & 

apps/web/app/hooks/features/useLanguageSettings.ts, apps/web/app/hooks/useLanguage.ts, apps/web/lib/settings/personal-setting-form.tsx
=> fix: display language list in dropdown on personnal settings page

apps/web/app/[locale]/kanban/page.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/lib/features/team-members-kanban-view.tsx
=> Fix/kanban UI

.cspell.json, apps/web/app/[locale]/auth/passcode/page.tsx, apps/web/app/[locale]/auth/team/page.tsx, apps/web/app/[locale]/board/page.tsx, apps/web/app/[locale]/integration/github/page.tsx, apps/web/app/[locale]/kanban/page.tsx, apps/web/app/[locale]/layout.tsx, apps/web/app/[locale]/meet/page.tsx, apps/web/app/[locale]/page.tsx, apps/web/app/[locale]/permissions/page.tsx, apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/app/[locale]/settings/personal/page.tsx, apps/web/app/[locale]/settings/team/page.tsx, apps/web/app/[locale]/task/[id]/page.tsx, apps/web/app/[locale]/team/[teamId]/[profileLink]/page.tsx, apps/web/app/[locale]/team/join/page.tsx, apps/web/app/[locale]/verify-email/page.tsx, apps/web/app/interfaces/AppProps.ts, apps/web/app/interfaces/hooks.ts, apps/web/app/stores/fullWidth.ts, apps/web/lib/components/container.tsx, apps/web/lib/layout/main-header.tsx, apps/web/lib/layout/main-layout.tsx, apps/web/lib/layout/navbar.tsx, apps/web/lib/settings/JitsuRoot.tsx
- Add Jitsu config for all pages 
- Add fullWidth of all pages
=> Feat/jitsu: add Jitsu config to all page

apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/app/[locale]/task/[id]/page.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/team/user-team-card/index.tsx
- Fix task info, Estimate and Task assignees
- also Dropdown centered
- Fix Task info width
=> Fix: cards columns style and width and breadcumbs links

apps/web/app/helpers/array-data.ts, apps/web/app/hooks/features/useTimeSlot.ts, apps/web/lib/components/progress-bar.tsx, apps/web/lib/features/activity/components/screenshoots-per-hour-skeleton.tsx, apps/web/lib/features/activity/components/screenshoots-per-hour.tsx, apps/web/lib/features/activity/screenshoots.tsx
- Sort and group screenshots list by startTime
- Add dynamic colors to Progress bar based on percent
=> Feat: improve screenshots tab page 

apps/web/app/api/timer/daily/route.ts, apps/web/app/helpers/array-data.ts, apps/web/app/hooks/features/useTimeDailyActivity.ts, apps/web/app/interfaces/timer/ITimerApp.ts, apps/web/app/services/client/api/activity/activity.ts, apps/web/app/services/client/api/index.ts, apps/web/app/services/server/requests/timer/daily.ts, apps/web/app/stores/time-slot.ts, apps/web/lib/features/activity/apps.tsx, apps/web/lib/features/activity/components/app-visited-Item.tsx, apps/web/lib/features/activity/components/app-visited-skeleton.tsx, apps/web/lib/features/activity/components/screenshoots-per-hour.tsx, apps/web/messages/en.json, apps/web/messages/fr.json, apps/web/messages/it.json, apps/web/messages/pl.json, apps/web/messages/pt.json, apps/web/messages/ru.json, apps/web/public/locales/en/common.json, apps/web/public/locales/fr/common.json, apps/web/public/locales/it/common.json, apps/web/public/locales/pl/common.json, apps/web/public/locales/pt/common.json, apps/web/public/locales/ru/common.json
=> feat: get daily apps visited

apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/app/hooks/features/useTimeDailyActivity.ts, apps/web/app/hooks/features/useTimeSlot.ts, apps/web/app/services/client/api/activity/activity.ts, apps/web/app/services/client/api/timer/timer-status.ts, apps/web/app/services/server/requests/timer/status.ts, apps/web/app/stores/time-slot.ts, apps/web/lib/features/activity/apps.tsx, apps/web/lib/features/activity/components/app-visited-details.tsx, apps/web/lib/features/activity/screenshoots.tsx, apps/web/lib/settings/JitsuRoot.tsx
- Conneted User Profile page
- Other team Member Profil Page (if Connected User is not a Manager)
=> feat: Show activity Tabs for connected user profil and Manger only

apps/web/app/hooks/features/useTimeDailyActivity.ts, apps/web/app/hooks/features/useTimeSlot.ts, apps/web/app/interfaces/IScreenshoot.ts, apps/web/lib/features/activity/apps.tsx, apps/web/lib/features/activity/components/screenshoots-per-hour.tsx, apps/web/lib/features/activity/components/screenshot-item.tsx, apps/web/lib/features/activity/screenshoots.tsx, apps/web/lib/features/activity/visited-sites.tsx, apps/web/lib/features/index.ts, apps/web/lib/features/team-members-block-view.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/task-skeleton.tsx, apps/web/lib/features/team/user-team-card/user-team-card-activity.tsx
=> Feat: Show Team Member Activity on Team Page

apps/web/app/api/organization-team-join/[id]/[action]/route.ts, apps/web/app/api/organization-team-join/resend-code/route.ts, apps/web/app/api/organization-team-join/validate/route.ts, apps/web/app/api/tags/[id]/route.ts, apps/web/app/api/tags/route.ts, apps/web/app/api/task-priorities/[id]/route.ts, apps/web/app/api/task-priorities/route.ts, apps/web/app/hooks/features/useTaskLabels.ts, apps/web/app/hooks/features/useTaskPriorities.ts, apps/web/app/services/client/api/request-to-join-team.ts, apps/web/app/services/client/api/task-labels.ts, apps/web/app/services/client/api/task-priorities.ts, apps/web/app/services/client/axios.ts, apps/web/components/layout/header/request-to-join-modal.tsx
- POST /organization-team-join/validate
- POST /organization-team-join/resend-code
- POST /tags
- PUT /organization-team-join/{id}/{action}
- PUT /tags/{id}
- DELETE /tags/{id}
- POST /task-priorities
- PUT /task-priorities/{id}
- DELETE /task-priorities/{id}
=> Feat/Next-Frontend APIs

apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/app/[locale]/task/[id]/page.tsx, apps/web/app/hooks/features/useOrganizationTeams.ts, apps/web/app/hooks/features/useTimeDailyActivity.ts, apps/web/app/hooks/features/useTimeSlot.ts, apps/web/app/hooks/features/useUserDetails.ts, apps/web/app/hooks/features/useUserProfilePage.ts, apps/web/app/interfaces/IActivityFilter.ts, apps/web/app/services/client/api/activity/activity.ts, apps/web/app/stores/activity-type.ts, apps/web/components/ui/svgs/expand.tsx, apps/web/lib/features/activity/apps.tsx, apps/web/lib/features/activity/screenshoots.tsx, apps/web/lib/features/activity/task-activity.tsx, apps/web/lib/features/activity/visited-sites.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/user-team-card-activity.tsx, apps/web/lib/features/team/user-team-card/user-worked-task.tsx
=> Feat: Display Worked Tasks to Activity section in Team Member Card

apps/web/lib/features/task/activity/user-task-activity.tsx, apps/web/lib/features/task/task-activity.tsx, apps/web/lib/settings/JitsuRoot.tsx, apps/web/package.json
- Fix Font Size on Activity 
- `Members Activity` Card and Items collapsible
- Display Slots of Member activity
=> [fix]: Activity Of Task

.cspell.json, apps/web/app/[locale]/layout.tsx, apps/web/next.config.js
- fix fonts ( By using next/font/google
=> fix: errors

apps/web/app/[locale]/kanban/page.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/features/team-members-kanban-view.tsx
Scroll Fix of kanban tasks movement 
Added the scroll at the bottom of page 
Responsive Fix of header in kanban
=> fix(Kanban): fixed the kanban scroll on task move + added the scroll

apps/web/app/hooks/auth/useAuthenticationPasscode.ts
re-route to login again is fix now it will only move to home page.
=> fix(Authentication): fix the authentication issue of re route to login

apps/web/app/[locale]/kanban/page.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/features/team-members-kanban-view.tsx, apps/web/lib/layout/main-layout.tsx
[kanban-scrolling-fix.webm](https://github.com/ever-co/ever-teams/assets/105014311/4acfc951-f010-47ad-9bcd-ee1c0dd76acc)
=> fix(Kanban): fix the kanban scrolling issue

apps/web/app/services/server/requests/public-organization-team.ts, apps/web/messages/ar.json, apps/web/messages/bg.json, apps/web/messages/de.json, apps/web/messages/en.json, apps/web/messages/es.json, apps/web/messages/fr.json, apps/web/messages/he.json, apps/web/messages/it.json, apps/web/messages/nl.json, apps/web/messages/pl.json, apps/web/messages/pt.json, apps/web/messages/ru.json, apps/web/messages/zh.json, apps/web/types/local.ts
Sir i've created a new file in web/types/local.ts which is not doing anything for the project but it through some error if some translation exist in `en` and not exist in other langauges
=> fix(Localization): fix the localization of web app

apps/web/app/[locale]/kanban/page.tsx, apps/web/lib/features/team-members-kanban-view.tsx
[full-scroll-kanban.webm](https://github.com/ever-co/ever-teams/assets/105014311/847bfa0c-9092-4510-bba9-a9452c11fe31)
=> 2208 fix kanban scrolling

apps/web/app/hooks/auth/useAuthenticationPasscode.ts
This error is not working because api is returning response `code:201` with message `"Unauthorized"` 
key: https://api.ever.team/api/auth/signin.email/confirm?includeTeams=true
So I just check that if the message is unauthorized or not
=> [Fix]: invalid code error fix

apps/web/lib/layout/auth-layout.tsx
=> [Fix]: height of login section bottom section

apps/web/app/[locale]/auth/passcode/page.tsx, apps/web/app/[locale]/team/join/page.tsx, apps/web/lib/components/inputs/auth-code-input.tsx
[reset-login-view.webm](https://github.com/ever-co/ever-teams/assets/105014311/763534ab-27ed-4e5a-8a58-15b024218cc9)
=> [Feature]: 2216 add reset button in code enterence on auth pages

apps/web/app/[locale]/kanban/page.tsx, apps/web/app/hooks/features/useKanban.ts, apps/web/components/ui/svgs/circular-progress.tsx, apps/web/lib/components/image-overlapper.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/lib/features/team-members-kanban-view.tsx
=> [UI]: design card of kanban is fixed

apps/web/app/[locale]/kanban/page.tsx
[kanban-header-scrolling.webm](https://github.com/ever-co/ever-teams/assets/105014311/4fa3559b-6cc1-40d2-8ec5-385e43dff853)
=> [UI]: kanban page header scrolling dropdown

apps/web/lib/features/user-nav-menu.tsx
=> [Feature]: adding scrolling on dropdown menu

.cspell.json, apps/web/app/[locale]/page-component.tsx, apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/app/[locale]/settings/layout.tsx, apps/web/app/[locale]/settings/personal/page.tsx, apps/web/app/[locale]/settings/team/page.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/lib/features/user-profile-tasks.tsx, apps/web/lib/settings/invitation-table.tsx
* fix: Email Input on Invite Pop Up
* fix: Tasks Tab on Profile Page
* fix: horizontal scroll on Invitation Table
* fix: spell words
* fix: Settings Header Page
* fix: restore AutoCompleteDropdown for emails in Invite
=> Fix: Errors (#2254)

apps/web/app/[locale]/page-component.tsx, apps/web/app/[locale]/settings/layout.tsx, apps/web/lib/components/container.tsx, apps/web/lib/components/toggler.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/task-skeleton.tsx, apps/web/lib/features/user-nav-menu.tsx, apps/web/lib/features/user-profile-tasks.tsx, apps/web/lib/layout/main-layout.tsx, apps/web/lib/settings/left-side-setting-menu.tsx, apps/web/next.config.js, apps/web/styles/globals.css
https://github.com/ever-co/ever-teams/assets/83704005/baed336a-392c-45c4-a5e5-f81362c45350
=> Feat: Full Width Switch Mode

apps/web/app/[locale]/kanban/page.tsx, apps/web/app/hooks/features/useKanban.ts, apps/web/app/hooks/features/useTeamTasks.ts, apps/web/components/pages/kanban/create-task-modal.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/components/image-overlapper.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/lib/features/task/task-input-kanban.tsx
* fix(kanban): working on kanban section
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
=> 2277 feature modifications in kanban 2 (#2290)

apps/web/app/[locale]/kanban/page.tsx, apps/web/lib/layout/main-layout.tsx
* fix(web): [kanban] fix horizontal scroll on kanban page
* 2277 feature modifications in kanban 2 (#2290)
* fix(kanban): working on kanban section
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
* [Fix]: added the kanban create task
---------
=> Fix/scroll effect (#2294)

apps/web/app/[locale]/page-component.tsx, apps/web/components/pages/main/header-tabs.tsx, apps/web/components/ui/data-table.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/lib/features/task/task-all-status-type.tsx, apps/web/lib/features/team-member-cell.tsx, apps/web/lib/features/team-members-block-view.tsx, apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team-members-table-view.tsx, apps/web/lib/features/team-members.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx, apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx
[pages-switch-glitch.webm](https://github.com/ever-co/ever-teams/assets/105014311/56592c60-a394-47d6-87ac-26cda8ba73fc)
=> [Fix]: fix the header tabs of home-pages

apps/web/app/[locale]/layout.tsx
this will only navigate to maintenence page.
=> [Bug]: maintainence navigation

apps/web/lib/components/Kanban.tsx, apps/web/lib/components/image-overlapper.tsx, apps/web/lib/components/kanban-card.tsx, apps/web/lib/features/task/task-all-status-type.tsx, apps/web/lib/features/task/task-input-kanban.tsx, apps/web/lib/features/task/task-issue.tsx
[kanban-labels.webm](https://github.com/ever-co/ever-teams/assets/105014311/58493f94-54b5-4402-9ec9-dda06c09bf91)
=> [Feature]: labels slider + drag header + create task label.

apps/web/app/[locale]/page-component.tsx, apps/web/components/ui/data-table.tsx, apps/web/lib/features/team-member-header.tsx, apps/web/lib/features/team-members-block-view.tsx, apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team-members-table-view.tsx, apps/web/lib/features/team-members.tsx, apps/web/lib/features/team/user-team-block/user-team-block-header.tsx, apps/web/lib/features/team/user-team-card/task-skeleton.tsx, apps/web/lib/features/team/user-team-table/user-team-table-header.tsx, apps/web/lib/layout/main-header.tsx
- Dark and Light Mode
- 
https://github.com/ever-co/ever-teams/assets/83704005/de24e2ba-9679-4dd5-ade9-d7995b11b7d2
- FullWidth vs Container Width Mode
https://github.com/ever-co/ever-teams/assets/83704005/f8976c54-5914-454d-9d0e-24df06e98e33
=> Fix: Task Input section & Headers  Team Members Views 

apps/web/lib/features/task/task-all-status-type.tsx, apps/web/lib/features/team-member-cell.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx
=> fix: align task Summary on Team Member List View ( Card & Table)

apps/web/lib/features/activity/components/screenshoots-per-hour.tsx, apps/web/lib/features/activity/components/screenshot-item.tsx, apps/web/lib/features/team/user-team-card/user-team-card-activity.tsx
=> Fix: Team Member & Improvements of UI

apps/web/app/[locale]/settings/layout.tsx, apps/web/app/[locale]/settings/team/page.tsx, apps/web/lib/components/pagination.tsx
[setting-view.webm](https://github.com/ever-co/ever-teams/assets/105014311/af13c54b-c108-4be2-83a7-a704725d2f3c)
=> [Design]: design setting and re-fetch

apps/web/app/[locale]/kanban/page.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/features/team-members-kanban-view.tsx, apps/web/lib/features/team/user-team-card/index.tsx
=> 2338 bug synchronize task progression in kanban view

apps/web/app/[locale]/kanban/page.tsx, apps/web/app/hooks/features/useKanban.ts, apps/web/components/pages/kanban/edit-status-modal.tsx, apps/web/lib/components/Kanban.tsx, apps/web/lib/features/team-members-kanban-view.tsx
[Apex_1712265369122.webm](https://github.com/ever-co/ever-teams/assets/105014311/4d6f240c-6b9c-438d-995a-edd3963a1ca2)
=> [Feature]: Edit Status for Kanban

apps/web/app/[locale]/kanban/page.tsx, apps/web/app/[locale]/layout.tsx, apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/lib/components/image-overlapper.tsx, apps/web/lib/features/task/task-item.tsx, apps/web/lib/features/team/user-team-block/user-info.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx, apps/web/lib/features/user-nav-menu.tsx
=> [Fix]: Head Document title

apps/web/app/[locale]/settings/layout.tsx, apps/web/app/hooks/useLeftSettingData.ts, apps/web/components/ui/scroll-bar.tsx, apps/web/lib/components/color-picker.tsx, apps/web/lib/components/dropdown.tsx, apps/web/lib/components/pagination.tsx, apps/web/lib/settings/list-card.tsx, apps/web/lib/settings/member-setting.tsx, apps/web/lib/settings/personal-setting-form.tsx, apps/web/lib/settings/timezone-dropdown.tsx
=> [Setting]: fixed the settings page issues

.cspell.json, apps/web/app/[locale]/kanban/page.tsx, apps/web/app/[locale]/page-component.tsx, apps/web/components/ui/data-table.tsx, apps/web/lib/features/team-members-kanban-view.tsx, apps/web/lib/features/team-members-table-view.tsx, apps/web/lib/features/team-members.tsx, apps/web/lib/features/team/user-team-block/user-team-block-header.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx, apps/web/lib/features/team/user-team-card/task-skeleton.tsx, apps/web/lib/features/team/user-team-table/user-team-table-header.tsx, apps/web/lib/layout/main-layout.tsx, apps/web/messages/ar.json, apps/web/messages/bg.json, apps/web/messages/de.json, apps/web/messages/en.json, apps/web/messages/es.json, apps/web/messages/fr.json, apps/web/messages/he.json, apps/web/messages/it.json, apps/web/messages/nl.json, apps/web/messages/pl.json, apps/web/messages/pt.json, apps/web/messages/ru.json, apps/web/messages/zh.json
[header-fixes.webm](https://github.com/ever-co/ever-teams/assets/105014311/d8715207-21b0-4443-8ca0-2024e0367d09)
=> 2371 bug home page fixes

apps/web/lib/components/Kanban.tsx
=> fix(Color): z-index added for color dropdown

apps/web/lib/components/dropdown.tsx
[Apex_1714415486711.webm](https://github.com/ever-co/ever-teams/assets/105014311/a4161a1c-9350-4a1e-a3dc-6459e5ae65b7)
=> 2401 bug team selector collapse does not work

apps/web/app/[locale]/settings/personal/page.tsx, apps/web/app/[locale]/settings/team/page.tsx, apps/web/lib/settings/table-action-popover.tsx
bug: dropdowns absolute bottom
before 
after
=> [Bug]: dropdown moving to bottom.

apps/mobile/app/services/client/requests/organization-team.ts, apps/web/app/services/client/api/public-organization-team.ts, apps/web/app/services/server/requests/public-organization-team.ts
@evereq Can you please merge this PR ASAP?
=> [Fix] Spelling Typo 

apps/web/lib/components/inputs/input.tsx, apps/web/lib/features/task/task-input.tsx, apps/web/package.json, yarn.lock
[Screencast from 04-05-2024 19:37:50.webm](https://github.com/ever-co/ever-teams/assets/97834160/0c9b69a8-516a-4c17-80ab-7fbf04012675)
=> [Feature] Add emojies to the input fields

apps/web/app/api/daily-plan/task/[taskId]/route.ts, apps/web/app/hooks/features/useDailyPlan.ts, apps/web/app/services/client/api/daily-plan.ts, apps/web/app/services/server/requests/daily-plan.ts, apps/web/app/stores/daily-plan.ts, apps/web/components/pages/task/details-section/blocks/task-plans.tsx, apps/web/components/pages/task/task-details-aside.tsx
=> Task details page "Planned" Block

apps/web/components/ui/popover.tsx, apps/web/lib/components/color-picker.tsx
=> Fix : [Bug] Dashboard | Can't create Label

apps/web/app/hooks/features/useTaskEstimation.ts, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/task-estimate.tsx
=> bug: header loading and estimate fixes

apps/web/lib/features/task/task-input.tsx
=> feat: fix the overflow issue

apps/web/app/[locale]/settings/layout.tsx
=> fix: breadcrumbs issue in setting page

apps/web/lib/components/inputs/input.tsx
[Screencast from 18-05-2024 21:56:20.webm](https://github.com/ever-co/ever-teams/assets/97834160/899a787c-380d-4c23-9cab-45ce6f391d4d)
=> [Improve] Close emoji selector when the user selects one

apps/web/lib/layout/footer.tsx
Fix the switch theme button if the Chatwoo app shows at the bottom of the screen
=> fix: fix the chatwoo space of switch theme

apps/web/lib/components/image-overlapper.tsx, apps/web/lib/features/task/task-card.tsx
[Screencast from 19-05-2024 16:13:39.webm](https://github.com/ever-co/ever-teams/assets/97834160/c801daeb-db6e-48f6-8c47-20e61e8be147)
=> [Improve] Add the functionality to select multiple assignees

apps/web/app/[locale]/task/[id]/page.tsx, apps/web/app/hooks/features/useTimer.ts, yarn.lock
We use usePathname Next.js hook to get the current page. If the current page is the "Task" page, when the user clicks on the start button of the timer, we first set the active task to a displayed task
=> Ability to Track time on "Task" page

apps/web/lib/features/task/daily-plan/outstanding.tsx, apps/web/lib/features/task/daily-plan/past-tasks.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/user-profile-plans.tsx
Some missing null checks block rendering and generate errors
=> Fix task-card and plans null checks

apps/mobile/app/services/client/requests/auth.ts, apps/web/app/[locale]/auth/error/page.tsx, apps/web/app/[locale]/auth/social-logins-buttons.tsx, apps/web/app/api/auth/signin-email-social-login/route.ts, apps/web/app/services/client/api/auth.ts, apps/web/app/services/client/api/auth/invite-accept.ts, apps/web/app/services/server/requests/OAuth.ts, apps/web/app/services/server/requests/auth.ts, apps/web/auth.ts, apps/web/package.json, yarn.lock
This PR completes also this #2563 and add some other features and fixes
=> Next Auth Adapter callback functions

apps/web/components/pages/task/description-block/editor-toolbar.tsx, apps/web/components/pages/task/description-block/task-description-editor.tsx, apps/web/lib/components/inputs/input.tsx
[Screencast from 01-06-2024 14:46:58.webm](https://github.com/ever-co/ever-teams/assets/97834160/4d961bf9-2940-4b5e-bd3a-a1611d67e6c5)
[Screencast from 01-06-2024 14:58:06.webm](https://github.com/ever-co/ever-teams/assets/97834160/90c85e97-2170-4957-a527-070e659532ad)
=> Improve emoji picker to appear only when input is active

apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/app/hooks/features/useUserProfilePage.ts, apps/web/app/stores/user.ts, apps/web/lib/features/team/user-team-card/index.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx
* feat: member not found
* feat: member not found
* feat: member not found page working
* feat: working on user detail section
* feat: added accordion for user detail
* feat: added accordion for user detail
* feat: added accordion for user detail
* feat: added accordion for user detail
* feat: added accordion for user detail
=> [Feat] Show user detail in accordion (#2569)

apps/web/lib/features/task/task-assign-popover.tsx, apps/web/lib/features/task/task-input.tsx
[Screencast from 04-06-2024 21:36:55.webm](https://github.com/ever-co/ever-teams/assets/97834160/3b2d3e28-8071-447d-b233-235552ae2700)
=> [Improvement] Updated assign task popup height

apps/web/app/[locale]/page-component.tsx, apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/components/ui/resizable.tsx, apps/web/package.json, apps/web/styles/globals.css, yarn.lock
Note : On future PRs, we should add this features where needed to allow users to have a clean-up interfaces
[screencast-localhost_3030-2024_06_28-18_57_01.webm](https://github.com/ever-co/ever-teams/assets/86450367/0e033e4b-b5d6-4092-be4e-cfc5689a6e4c)
=> Resize tasks and members panels

apps/web/app/hooks/features/useTaskStatistics.ts, apps/web/components/ui/select.tsx, apps/web/lib/components/dropdown.tsx, apps/web/lib/features/task/daily-plan/index.ts, apps/web/lib/features/task/daily-plan/outstanding-all.tsx, apps/web/lib/features/task/daily-plan/outstanding-date.tsx, apps/web/lib/features/task/daily-plan/outstanding.tsx, apps/web/lib/features/task/daily-plan/task-estimated-count.tsx, apps/web/lib/features/user-profile-plans.tsx, apps/web/package.json, yarn.lock
Uploading Outstanding should have .mov…
1. Estimated time (overall [tasks);`[2626]`
3. Total tasks (display how many) @Cedric921
=> [fix]: Tab 'Outstanding' should have

apps/web/app/[locale]/settings/team/page.tsx, apps/web/lib/components/accordian.tsx
Block 'Invited Members' should be collapsed if there is no one who is pending.
=> feat: collapse the invitations accordion when there is no one

apps/web/app/[locale]/profile/[memberId]/page.tsx
[Uploading screencast-localhost_3030-2024_07_11-03_52_33.webm…]()
=> Hidden tabs and filters on profile page

apps/web/lib/features/task/daily-plan/future-tasks.tsx, apps/web/lib/features/user-profile-plans.tsx
Fix: Error on daily plan delete plan
@evereq 
@Cedric921
=> [Fix] Dailyplan Deleteplan

apps/web/app/[locale]/auth/password/component.tsx, apps/web/app/hooks/features/useDailyPlan.ts, apps/web/lib/settings/danger-zone-team.tsx
- This should also be fixed (when creating a new team)
- We should also delete the last selected team from the local storage if the user disposed it
=> fixbug: user should login and create a new team if there is no one

apps/web/lib/components/inputs/auth-code-input.tsx
[Apex_1721259702198.webm](https://github.com/user-attachments/assets/611dbf7e-24ac-4f0a-a6f9-871b3363e2de)
=> fix: auto show error after login

apps/web/app/[locale]/page-component.tsx, apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/lib/layout/main-layout.tsx
=> fix: remove unecessary paddings / margings on home and team page

apps/web/app/[locale]/kanban/page.tsx, apps/web/app/hooks/features/useKanban.ts, apps/web/lib/components/image-overlapper.tsx
[Loom video](https://www.loom.com/share/b9e78641578740acac60427dfb74feab?sid=1008eb08-3fed-42a5-ac18-7496722fd5ce)
=> fixbug: system should filter kanban page with tasks assigned to a member

apps/web/app/[locale]/page-component.tsx, apps/web/app/constants.ts, apps/web/app/helpers/daily-plan-estimated.ts, apps/web/lib/features/daily-plan/daily-plan-compare-estimate-modal.tsx
[Feature]  Daily Plan compare Estimated tasks time and Planned work hours #2614
https://github.com/user-attachments/assets/21667e2a-13ee-4f76-bd48-f29b3c0bb72d
=> [Feat]: Daily Plan Compare Estimated LOGIC

apps/web/app/[locale]/page-component.tsx, apps/web/app/helpers/daily-plan-estimated.ts, apps/web/app/helpers/date.ts, apps/web/lib/features/daily-plan/daily-plan-compare-estimate-modal.tsx, apps/web/lib/features/team-members-card-view.tsx
Daily Plan compare Estimated tasks time and Planned work hours
=> [Feat]: Daily Plan compare Estimated tasks time and Planned work hours

apps/web/app/helpers/plan-day-badge.ts, apps/web/lib/features/task/task-all-status-type.tsx
[Improvement] 'Daily Plan' | Badge colour of the past dates #2790
=> [Improvement]:The Planned + date badges should have the RED color 

apps/web/lib/features/team/team-outstanding-notifications.tsx
=> fixbug: fix outstanding notifications for manager role

apps/mobile/app/helpers/date.ts, apps/web/app/services/client/api/tasks.ts, apps/web/lib/components/custom-select/index.tsx, apps/web/lib/components/emoji-picker.tsx, apps/web/lib/components/index.ts, apps/web/lib/components/keyboard-shortcuts.tsx, apps/web/lib/components/toggler.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/styles/style.css
- The **SelectItems** component has been adjusted to be used more smoothly in popups, with improved handling of interactions and style based on the popup's open state.
https://github.com/user-attachments/assets/828041e5-0c84-41a7-8b15-8190ab5a96fa
https://github.com/user-attachments/assets/d42a83a3-72bd-4d51-82b9-e7e0998d6c94
=> [Improvement]: Customize select

apps/web/lib/features/task/daily-plan/future-tasks.tsx, apps/web/lib/features/task/daily-plan/past-tasks.tsx, apps/web/lib/features/user-profile-plans.tsx, apps/web/lib/features/user-profile-tasks.tsx
=> [Fix]: fix the delete button on the future tasks view

apps/web/app/hooks/features/useTaskEstimation.ts, apps/web/assets/common/loading.svg, apps/web/assets/svg.ts, apps/web/lib/components/inputs/input.tsx, apps/web/lib/features/task/task-estimate.tsx
@evereq, @KostyaEver, please check what I did [here](https://www.loom.com/share/cf4bf21114d847969d043d92dd3b3b5a?sid=bf85be38-3950-4cf7-8dd1-3da308fc6996)
=> refactor: Estimate | '0' hours should display in different way

apps/web/app/[locale]/auth/passcode/component.tsx, apps/web/app/hooks/auth/useAuthenticationPasscode.ts, apps/web/lib/components/custom-select/index.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/user-profile-tasks.tsx
- Show correct message for valid code but invalid password
- Updated validation logic for email and code verification
This solution also answers problem #2783
=> [FIX]: Show correct message for valid code but invalid password

apps/web/app/[locale]/all-teams/component.tsx, apps/web/app/[locale]/auth/passcode/component.tsx, apps/web/lib/features/task/task-card.tsx
[Fix]: Daily Plan Action Menu Displays
https://github.com/user-attachments/assets/f9e36017-2bd3-4902-bbfe-096c0fedd561
=> [Bug] 'Daily Plan' | Action menu displays restricted set of options

apps/web/lib/components/custom-select/index.tsx, apps/web/lib/features/task/task-filters.tsx
- Added `renderItem` prop to `SelectItems` component, allowing custom rendering of list items.
https://github.com/user-attachments/assets/bb8d9431-2f0f-49fd-afb0-e178b83a2f7b
=> [Feat]: Add dynamic rendering to SelectItems component

apps/web/lib/features/daily-plan/plans-work-time-and-estimate.tsx, apps/web/lib/features/timer/timer.tsx
The previous PR that intended to resole the issue had a little problem in the SOFT flow  ⇒  check if a user has already today tasks (which means having the today plan with some tasks added) so that we can show some content in the popup, otherwise show an empty popup (no action to do ⇒ block everything)
- Remove that check
=> fixbug: blocking any user to start working

apps/web/app/[locale]/page-component.tsx, apps/web/app/constants.ts, apps/web/app/interfaces/timer/IManualTimeReasons.ts, apps/web/lib/features/manual-time/add-manual-time-modal.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/locales/ar.json, apps/web/locales/bg.json, apps/web/locales/de.json, apps/web/locales/en.json, apps/web/locales/es.json, apps/web/locales/fr.json, apps/web/locales/he.json, apps/web/locales/it.json, apps/web/locales/nl.json, apps/web/locales/pl.json, apps/web/locales/pt.json, apps/web/locales/ru.json, apps/web/locales/zh.json
Modifications made for organization purpose:
- Create a files `add-manual-time-modal` under `/lib/features/manual-time`
- Move manual time related logic from `/lib/features/task/task-filters.tsx` to `/lib/features/manual-time/add-manual-time-modal.tsx`
Problems encountered (with previous merges) that need to be resolved:
- Direct API call inside JSX ⇾ PR tag : #2715 
- Default value for team and task select does no longer work ⇾ PR tag : #2798 
@evereq, @Cedric921, would you please create issues for these problems (listed above) ?
=> feat: add a select with predefined data | add manual time reasons

apps/web/lib/components/custom-select/index.tsx, apps/web/lib/features/manual-time/add-manual-time-modal.tsx
Now, the `addManualTime` preselects the current team / task and the default reason
=> refactor: refactor the SelecItems component to accept defaultValues

apps/web/app/hooks/features/useStartStopTimerHandler.ts, apps/web/lib/features/daily-plan/daily-plan-compare-estimate-modal.tsx, apps/web/lib/features/daily-plan/suggest-daily-plan-modal.tsx
This PR improves the SOFT flow popup logic, fixes #2680
=> Feat redirect to profil after plan suggestion

apps/web/app/hooks/features/useManualTime.ts, apps/web/app/interfaces/ITimer.ts, apps/web/app/interfaces/timer/ITimerLogs.ts, apps/web/app/services/client/api/timer/manual-time.ts, apps/web/lib/features/manual-time/add-manual-time-modal.tsx
[Loom](https://www.loom.com/share/ac6c731d4a274c44a494c66dd6c557b4?sid=400ef03a-b9ef-4858-bcde-c532ef3dba9d)
=> feat: separate api call from react component

.cspell.json, apps/web/app/[locale]/meet/livekit/component.tsx, apps/web/components/shared/collaborate/index.tsx, apps/web/lib/features/daily-plan/daily-plan-compare-estimate-modal.tsx, apps/web/lib/features/integrations/livekit/index.tsx, apps/web/lib/features/integrations/livekit/settings-livekit.tsx, apps/web/lib/utils.ts, apps/web/package.json, apps/web/styles/settings.module.css, apps/web/tailwind.config.js, yarn.lock
- Video Device Availability Check
- Audio Device Availability Check
- Meeting Link Sharing
- Custom Settings Interface:
=> Feat: Settings Component Integration

apps/web/lib/features/task/task-card.tsx
[Loom](https://www.loom.com/share/1eea2980276f4b05a1449d8fd23dc0bd?sid=a770a316-ec65-42ea-944e-ed146eebc359)
=> 2682 bug daily plan task action menu hidden UI

apps/web/lib/features/task/task-card.tsx
[Loom](https://www.loom.com/share/1fbb039cb88e43d6b99cd1ea8e3caede?sid=87ac5fff-2289-4c86-b1dd-fce68d697eb9)
=> fix: the same task should not be planned multiple times for the same day

apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/task/task-status.tsx, apps/web/lib/features/task/task-times.tsx, apps/web/lib/features/user-profile-tasks.tsx
[Loom](https://www.loom.com/share/1a622989f557442086e05496502c2007?sid=c2ceea95-8edf-4a5d-a255-aa34c980cd03)
=> fix: improve the delay when switching tabs (unassigend,assigned)

apps/web/app/hooks/features/useDailyPlan.ts
#2851 ->  #2841
This was the issue after adding a new task to the plan:
=> fix: remove duplication of today plan when adding a new task

apps/web/lib/features/task/task-card.tsx
. Combining todayPlan and futurePlans arrays to check for multiple occurrences of a task.
. Implementing a reduction logic to count task occurrences across different dates.
https://github.com/user-attachments/assets/d1c41563-edec-455a-a7ee-56309fad046c
=> [Feat]: Display Remove from all plans option only if task is planned

apps/web/lib/features/team/team-outstanding-notifications.tsx
=> fix: fix the number of outstanding tasks in notifications

apps/web/lib/features/timer/timer.tsx
=> fix: use the same logic for all start / stop timer button

apps/web/lib/features/task/task-filters.tsx
=> feat: remane the dailyplan tab name to Planned

apps/web/lib/features/daily-plan/create-daily-plan-form-modal.tsx, apps/web/lib/features/task/task-card.tsx
[Loom](https://www.loom.com/share/c9be5ddd76c9462c9e3bd4dce54a03b1?sid=7bcc76a7-ca4f-4692-97dc-7e064fb264de)
=> fix:  user should be able to close popup after selection the appropriate date

apps/web/lib/features/integrations/activity-calendar/index.tsx
- Added IDs to the legend items in ResponsiveCalendar for consistent referencing.
- Implemented a custom legend component (ActivityLegend) with corresponding IDs for each time range.
=> Feat: Add Custom legend with IDs and synchronize with ResponsiveCalendar

apps/web/lib/features/daily-plan/suggest-daily-plan-modal.tsx
=> refactor: improve the suggest daily plan modal

apps/web/lib/features/task/task-card.tsx
[Loom](https://www.loom.com/share/382d529bbf144b65a13941e01fbf7776?sid=caad9c1e-b818-4003-8bd2-d7f96cfd44ce)
=> fix: outstanding tasks should be able to plan as normal tasks

apps/web/app/[locale]/integration/github/component.tsx, apps/web/app/[locale]/page-component.tsx, apps/web/app/hooks/features/useDailyPlan.ts, apps/web/app/hooks/features/useTimeLogs.ts, apps/web/app/hooks/features/useTimeSlot.ts, apps/web/app/hooks/features/useTimer.ts, apps/web/app/hooks/features/useTimezoneSettings.ts, apps/web/app/hooks/useCallbackRef.ts, apps/web/app/hooks/useLiveKit.ts, apps/web/components/layout/header/position-dropdown.tsx, apps/web/components/pages/setting/interaction-observer.tsx, apps/web/components/pages/task/description-block/editor-footer.tsx, apps/web/components/shared/Observer/index.tsx, apps/web/lib/app/init-state.tsx, apps/web/lib/features/integrations/calendar/year-picker-filter.tsx, apps/web/lib/features/task/task-all-status-type.tsx, apps/web/lib/features/team-members-card-view.tsx, apps/web/lib/features/team/team-outstanding-notifications.tsx, apps/web/lib/settings/choose-dropdown.tsx, apps/web/lib/settings/color-dropdown.tsx, apps/web/lib/settings/day-dropdown.tsx, apps/web/lib/settings/filter-by-dropdown.tsx, apps/web/lib/settings/icon-dropdown.tsx, apps/web/lib/settings/invitation-expire-dropdown.tsx, apps/web/lib/settings/notify-dropdown.tsx, apps/web/lib/settings/page-dropdown.tsx, apps/web/lib/settings/period-dropdown.tsx, apps/web/lib/settings/proof-dropdown.tsx, apps/web/lib/settings/sort-by-dropdown.tsx
=> Tiny UI Improvements

apps/web/app/hooks/features/useTimeLogs.ts, apps/web/app/interfaces/timer/ITimerLogs.ts, apps/web/app/services/client/api/activity/time-logs.ts, apps/web/components/pages/task/details-section/blocks/task-main-info.tsx, apps/web/components/ui/data-table.tsx, apps/web/lib/features/team/user-team-card/index.tsx
[Bug] Fix permission issue for 'Stats' tab visibility on profiles #2902
https://github.com/user-attachments/assets/ca6e1a6b-4446-4c93-a568-e05ab5dd2ce2
=> [Bug]: permission issue for 'Stats' tab visibility on profiles

apps/web/lib/features/user-profile-plans.tsx
I added a minimum (0) value for the Planned work time input so that user cannot set negative values
=> fix: user should not be able to set negative values for planned work time

apps/web/lib/features/manual-time/add-manual-time-modal.tsx
https://github.com/user-attachments/assets/23b66bf2-e69d-4af1-baa5-7b6fc470596c
https://github.com/user-attachments/assets/0b26fb30-f595-4cfd-8e31-09385268f4d4
=> [Feat]: Dynamic Member Selection

apps/web/lib/components/time-picker/index.tsx, apps/web/lib/features/daily-plan/daily-plan-compare-estimate-modal.tsx, apps/web/lib/features/integrations/calendar/confirm-change-status.tsx, apps/web/lib/features/integrations/calendar/table-time-sheet.tsx, apps/web/lib/features/integrations/calendar/time-sheet-filter-popover.tsx
https://github.com/user-attachments/assets/b092762d-cfc9-4c8f-9a0b-a1a68e2db82a
https://github.com/user-attachments/assets/d386399d-4b43-4e8e-b0b1-33c4234acdc7
=> [Feature]: Confirm Status Change With Time Sheet

apps/web/lib/features/team/invite/invite-form-modal.tsx, apps/web/lib/features/user-profile-plans.tsx
…existing employee data
https://github.com/user-attachments/assets/7f10d0a1-0c66-4970-9677-06fd5fa01d6a
https://github.com/user-attachments/assets/0ddf9390-0a52-4716-a07f-3b6ee268f63a
=> [Feat]: Implement auto-complete for email domain and name pre-fill

apps/web/components/pages/task/ChildIssueCard.tsx, apps/web/components/pages/task/IssueCard.tsx
=> [Fix]: Resolve app crash on Task Page

apps/web/app/[locale]/calendar/page.tsx, apps/web/lib/features/integrations/calendar/confirm-change-status.tsx, apps/web/lib/features/integrations/calendar/setup-time-sheet.tsx, apps/web/lib/features/integrations/calendar/table-time-sheet.tsx
#2805
https://github.com/user-attachments/assets/dfd54aaa-9c1e-4090-b7cb-faf9e91a8663
https://github.com/user-attachments/assets/0e67d567-1072-4d01-aaf0-4ae58ee116e5
=> [Feat]: Add Badget Status, Select Filter status, Button delete

apps/web/app/hooks/features/useStartStopTimerHandler.ts, apps/web/components/shared/timer/timer-card.tsx, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/lib/features/daily-plan/enforce-planed-task-modal.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/timer/timer.tsx
If user has today plan with planned tasks:
-  Ask the user to add the selected task to the today plan if it is not included
- SOFT FLOW
[Loom](https://www.loom.com/share/56d44d39ae5947978505f9f0751c8fa8?sid=f01584da-42c4-4fc7-a3f8-099480607b30)
=> feat: ask the user to add selected task if it is not included in the today's plan

apps/web/lib/features/task/task-status.tsx, apps/web/lib/settings/task-statuses-form.tsx
This PR fixes #2949 
[Loom](https://www.loom.com/share/c3a9dd024138435faadc5b6fec150c0c?sid=885aee2e-4b6b-47fd-a53e-b6664dccb0db)
[Loom](https://www.loom.com/share/7f81dd9b9e7341b5aaba50a36eded64d?sid=14627793-4137-4550-9a2f-d9fe967f8139)
=> fix: aling elements with proper size on settings / Create new issue

apps/web/lib/features/all-teams-members-block-view.tsx, apps/web/lib/features/all-teams-members-card-view.tsx, apps/web/lib/features/all-teams/all-team-members-filter.tsx
=> 2742 improvement all teams UI for manager

apps/web/app/hooks/features/useTimer.ts, apps/web/lib/components/lazy-render.tsx, apps/web/lib/features/task/task-input.tsx
Fix infinite time-slot requests when timer is active
- Fix #2960
-   [ x] Bug fix
=> Fix infinite time-slot requests

apps/web/lib/components/combobox/index.tsx, apps/web/lib/features/manual-time/add-manual-time-modal.tsx
#2805
https://github.com/user-attachments/assets/903bc090-d1eb-4fa5-b940-d72a2a946b4d
=> [Feat]: Add generic CustomCombobox component with props for dynamic

apps/web/app/[locale]/calendar/page.tsx, apps/web/lib/components/combobox/index.tsx, apps/web/lib/features/manual-time/add-manual-time-modal.tsx, apps/web/lib/features/manual-time/manage-member-component.tsx
-   [x] Breaking change
-   [x] Documentation update
https://github.com/user-attachments/assets/83c61942-7131-4159-b190-1ad55f1ba3a2
=> [Feat]: Adapt ManageOrMemberComponent to new design with dynamic fields and combobox

apps/web/app/hooks/features/useDailyPlan.ts, apps/web/components/ui/calendar.tsx, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/lib/features/daily-plan/all-plans-modal.tsx, apps/web/lib/features/daily-plan/create-daily-plan-form-modal.tsx, apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx
This PR fixes #2892 
[Loom](https://www.loom.com/share/a6db343e8de64fec9b2e51c2d46287c1?sid=fb64f14f-2a55-42b0-9a8a-5072dfe48126)
=> [Feat] Team card member | See all plans modal

apps/web/lib/components/sidebar-accordian.tsx
=> fix arrow direction in settings sidebar

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
This PR fixes #2999 
[Loom](https://www.loom.com/share/599bdf32a2934a31b950207f43442b4f?sid=f8d75839-9256-44b9-b845-28512b4a2d3a)
[Loom](https://www.loom.com/share/980dc80a09cc419d8ec9ca0a58abe4f8)
=> fix: trim leading zeros at the beginning of work time planned

apps/web/components/ui/calendar.tsx, apps/web/lib/features/daily-plan/all-plans-modal.tsx
=> 3001 bug planned  years months have not values

apps/web/components/ui/calendar.tsx, apps/web/lib/features/daily-plan/all-plans-modal.tsx
This PR fixes #3008 
[Loom](https://www.loom.com/share/e8da9f0671f04318abf71d8885eea22a)
=> 3008 improvements see plan  user should be able to see all plans on the calendar

apps/web/components/ui/data-table.tsx, apps/web/components/ui/table.tsx, apps/web/lib/features/team-member-cell.tsx, apps/web/lib/features/team/user-team-card/task-estimate.tsx, apps/web/lib/features/team/user-team-card/task-info.tsx, apps/web/lib/features/team/user-team-card/user-info.tsx
This PR fixes  #2991 
[Loom](https://www.loom.com/share/625a8009297543b487c1a5051b44d146)
=> fix overlap on team member card| table view

apps/web/lib/features/manual-time/add-manual-time-modal.tsx
=> [Fix]: Typing Error Member Items Lists

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
This PR fixes #3036 
[Loom](https://www.loom.com/share/324ad000642245248f719ed3c6e7b2b9?sid=4c5aa4dd-07d2-4836-a5a4-771e8bc87210)
=> feat: disable actions on all past plans / add new details

apps/web/app/constants.ts, apps/web/lib/features/team/team-outstanding-notifications.tsx, apps/web/lib/features/user-profile-plans.tsx
This PR fixes #3029 
[Loom](https://www.loom.com/share/2318396623e5481991b1c42a5b64291d?sid=e4d5491e-6943-43e5-88ee-916779c27524)
[Loom](https://www.loom.com/share/a99f5dc02aba48528ea9ad8ad2115020?sid=474179e0-c947-472d-8b18-6950881dea90)
=> feat: should hide ouststanding notification after visit outstating tab

apps/web/app/hooks/features/useDailyPlan.ts
=> fixbug: fix unhandled exception when no items in profilePlans

apps/web/app/hooks/features/useDailyPlan.ts, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/lib/features/daily-plan/unplan-active-task-modal.tsx
This PR fixes #3022 
[Loom](https://www.loom.com/share/b6a510da0e8749818a2de3f1cfa7a155?sid=04b24150-c337-4381-85aa-d2d9703d20a8)
=> 3022 improvement see plan  the timer is running and user addsremove a task to the plan

apps/web/app/[locale]/page-component.tsx, apps/web/app/[locale]/profile/[memberId]/page.tsx, apps/web/lib/components/notifications-dropdown/index.tsx, apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/team-member-header.tsx, apps/web/lib/features/team/team-invitations.tsx, apps/web/lib/features/team/user-team-card/task-skeleton.tsx, apps/web/lib/features/team/user-team-table/user-team-table-header.tsx, apps/web/lib/features/user-profile-plans.tsx, apps/web/lib/layout/navbar.tsx, apps/web/locales/ar.json, apps/web/locales/bg.json, apps/web/locales/de.json, apps/web/locales/en.json, apps/web/locales/es.json, apps/web/locales/fr.json, apps/web/locales/he.json, apps/web/locales/it.json, apps/web/locales/nl.json, apps/web/locales/pl.json, apps/web/locales/pt.json, apps/web/locales/ru.json, apps/web/locales/zh.json
What I did optimize the spacing in home and profile pages
=> 3014 improvement common  scrolling zones on pages

apps/web/app/hooks/features/useDailyPlan.ts, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/lib/features/daily-plan/all-plans-modal.tsx, apps/web/lib/features/team/user-team-card/task-skeleton.tsx, apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx, apps/web/locales/ar.json, apps/web/locales/bg.json, apps/web/locales/de.json, apps/web/locales/en.json, apps/web/locales/es.json, apps/web/locales/fr.json, apps/web/locales/he.json, apps/web/locales/it.json, apps/web/locales/nl.json, apps/web/locales/pl.json, apps/web/locales/pt.json, apps/web/locales/ru.json, apps/web/locales/zh.json
This PR fixes #3007 
[Loom](https://www.loom.com/share/8e366e31f01b4f73a941734ac23d0fba?sid=62a52cd7-2f55-4655-9fc2-a6daa66bdb48)
=> 3007 improvement see plan  add ability to createedit plan

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/locales/ar.json, apps/web/locales/bg.json, apps/web/locales/de.json, apps/web/locales/en.json, apps/web/locales/es.json, apps/web/locales/fr.json, apps/web/locales/he.json, apps/web/locales/it.json, apps/web/locales/nl.json, apps/web/locales/pl.json, apps/web/locales/pt.json, apps/web/locales/ru.json, apps/web/locales/zh.json
=> 3061 improvement see plan  past plans view

apps/web/lib/components/modal.tsx, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/lib/features/daily-plan/all-plans-modal.tsx
This PR fixes #3062
[Loom](https://www.loom.com/share/cb02882e2a944741a9c1ec70b03063f5?sid=ed7aa335-515e-42ad-98b9-8cb26438e1a3)
[Loom](https://www.loom.com/share/00569a35a8d34760a162e84cf92fb284?sid=e7fe30f7-5a09-4419-8e05-6afe333b33a8)
=> fix dropdowns in 'See plan' modal

apps/web/lib/features/daily-plan/all-plans-modal.tsx
This PR fixes #3063 
[Loom](https://www.loom.com/share/3b4c6e5c68474ecebe3ad0f2c8f41551?sid=2b1974c8-1497-4afe-9491-46f5f40881c9)
=>  user is  able to double-click on specific dates and see a Plan

apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
=> feat: improve the warnings order in the Daily plan modal

apps/web/app/helpers/date.ts, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx
=> 2970 improvement planned  total estimate logic

apps/web/lib/features/daily-plan/all-plans-modal.tsx
=> 3086 improvement see plan  add arrows back forward

apps/web/lib/components/kanban-card.tsx
This PR fixes #2411 
[Loom](https://www.loom.com/share/e72a2023466c49bd887b0f15f1b9ee65?sid=c24dadff-92cf-4cb9-bf5f-a4750105acc9)
=> fix: show live time for task on which the user is working

apps/web/lib/features/task/task-filters.tsx, apps/web/lib/features/user-profile-plans.tsx
=> set the tab to outstanding if there are outstanding tasks next day

apps/web/app/hooks/features/useStartStopTimerHandler.ts, apps/web/components/shared/timer/timer-card.tsx, apps/web/lib/features/daily-plan/add-task-estimation-hours-modal.tsx, apps/web/lib/features/daily-plan/enforce-planed-task-modal.tsx, apps/web/lib/features/task/task-card.tsx, apps/web/lib/features/timer/timer.tsx
This PR adds enforce plan flow
[Loom](https://www.loom.com/share/5779b54a71c74a0397af88ac2e524dfd?sid=41831b69-f7c2-45bc-9891-2450b32d7b6a)
=> add enforce plan flow

apps/mobile/eas.json
=> Improve eas file

apps/mobile/eas.json
=> Remove ios submit temporary

apps/mobile/eas.json
=> Add ios credentials

.github/workflows/mobile.apps.android.yml, .github/workflows/mobile.apps.ios.yml, .github/workflows/mobile.apps.stage.android.yml, .github/workflows/mobile.apps.stage.ios.yml
=> Add default values for package name and bundle identifier

.github/workflows/mobile.apps.ios.yml, .github/workflows/mobile.apps.stage.ios.yml
=> Update eas publish command

apps/mobile/eas.json
=> Rename apple private key file name

apps/mobile/.env
=> trigger ios build

apps/mobile/.env, apps/mobile/eas.json
=> Release iOS

apps/mobile/eas.json
=> Update ios prod submit

apps/mobile/app.template.json
=> Define use of encryption for ios

apps/mobile/app.template.json, apps/mobile/eas.json
=> Testing release

SECURITY.md
* chore: update license reference
* Update SECURITY.md
---------
=> chore: update license reference (#3468)

apps/web/components/offline-wrapper/index.tsx
=> [Fix]: Ensure useNetworkState is used only in client-side context

apps/mobile/app.template.json
=> Update permission message

apps/web/app/[locale]/timesheet/[memberId]/components/TimesheetPagination.tsx, apps/web/app/[locale]/timesheet/[memberId]/page.tsx
-   [x] I have made corresponding changes to the documentation
=> [Feat]: Add rows per page

apps/web/app/[locale]/projects/components/data-table.tsx, apps/web/app/[locale]/projects/components/page-component.tsx, apps/web/app/constants.ts, apps/web/app/hooks/features/useOrganizationProjects.ts, apps/web/app/hooks/features/usePagination.ts, apps/web/app/interfaces/IProject.ts, apps/web/app/services/client/api/organization-projects.ts, apps/web/lib/features/project/add-or-edit-project/container.tsx, apps/web/lib/features/project/add-or-edit-project/index.tsx, apps/web/lib/features/project/add-or-edit-project/steps/basic-information-form.tsx, apps/web/lib/features/project/add-or-edit-project/steps/categorization-form.tsx, apps/web/lib/features/project/add-or-edit-project/steps/financial-settings-form.tsx, apps/web/lib/features/project/add-or-edit-project/steps/review-summary.tsx, apps/web/lib/features/project/add-or-edit-project/steps/team-and-relations-form.tsx, apps/web/lib/features/project/add-or-edit-project/text-editor/index.tsx, apps/web/lib/features/project/add-or-edit-project/utils.ts
- Close #3332 
- Close #3319
- Remove labels in the project creations steps
- Hide project relations in the project creations steps
-   [x] I have commented on my code, particularly in hard-to-understand areas
[Loom](https://www.loom.com/share/2dd20475eae84894a1e6c61f8560ff7e?sid=82432bac-7e1c-4340-bfc9-155347497850)
=> [Feature] Project management | Edit existing project

apps/mobile/app/components/TextField.tsx, apps/mobile/app/components/Toggle.tsx, apps/mobile/app/navigators/navigationUtilities.ts, apps/mobile/app/screens/Authenticated/SettingScreen/components/ChangeTeamLogo.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/components/ChangeUserAvatar.tsx, apps/mobile/app/screens/Authenticated/SettingScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskLabelScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskPrioritiesScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskSizeScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskStatusScreen/index.tsx, apps/mobile/app/screens/Authenticated/TaskVersionScreen/index.tsx, apps/mobile/app/screens/DemoPodcastListScreen.tsx, apps/mobile/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx, apps/mobile/app/screens/DemoShowroomScreen/DrawerIconButton.tsx, apps/mobile/app/screens/DemoShowroomScreen/demos/DemoListItem.tsx, apps/mobile/app/screens/LoginScreen/Components/FillTeamNameForm.tsx, apps/mobile/app/screens/LoginScreen/Components/FillUserInfoForm.tsx, apps/mobile/app/screens/LoginScreen/Components/PassCode.tsx, apps/mobile/app/services/hooks/features/useAuthenticationTeam.ts, apps/mobile/app/services/reactotron/reactotron.ts, apps/mobile/app/services/reactotron/reactotronClient.ts, apps/mobile/package.json, apps/mobile/tsconfig.json, apps/mobile/yarn.lock
=> Fix build errors due to some libs upgrade

apps/mobile/babel.config.js, apps/mobile/yarn.lock
=> Fix some small issues

apps/mobile/app.template.json, apps/mobile/yarn.lock
=> Improve ios target version

apps/web/app/[locale]/team/tasks/page.tsx, apps/web/app/hooks/features/useOrganizationTeamManagers.ts, apps/web/components/pages/team/tasks/TaskTable.tsx, apps/web/components/pages/team/tasks/columns.tsx, apps/web/components/pages/team/tasks/tasks-data-table.tsx, apps/web/lib/components/pagination.tsx
- Implement the search feature
- Implement the view toggles
- Fix font and table header
[Loom](https://www.loom.com/share/9ff485042f054bfb8d8b164901e54a2c?sid=62072249-b88e-4eb7-930b-2224070250de)
=> [Task] Implement search on the team tasks list and column views

apps/web/core/hooks/auth/use-authentication-passcode.ts, apps/web/core/services/client/api/auth/auth.service.ts, apps/web/core/types/interfaces/IAuthentication.ts
Fixed invite code validation bug that was causing 400 Bad Request errors during authentication. The issue was due to incorrect endpoint usage and missing parameters. This change simplifies the authentication flow by using a direct login approach that reduces API calls and improves error handling.
This PR streamlines the authentication flow by implementing a direct login approach with improved error handling and workspace selection functionality.
* Simplified auth flow in `auth.service.ts` using `/auth/login` as primary endpoint with `/auth/signin.email/confirm` fallback
* Added team property to `ILoginResponse` and `ISigninEmailConfirmResponse` interfaces for workspace selection support
* Implemented two-step authentication in `use-authentication-passcode.ts` with proper error handling …
=> [Bug Fix][WEB]: Fix invite code authentication flow and improve security

apps/mobile/tsconfig.json
_A short and clear title that describes what this PR does._
Example:
> Add Retry, Cache, and Logging Features to API Service
Please describe **what you did**, and **why**.
- What problem or feature does this PR address?
- What changes were made?
- Why are these changes useful?
Example:
> This PR adds advanced features to the API request system:
>
> - Retry failed requests with exponential delay
> - Cache GET responses with TTL
> - Log all requests and responses
> - Allow cancelling requests
>
> These features improve reliability, performance, and debugging.
Example:
> Here are the major changes in that his PR adds
>
> - New `CookieManagement` class for cookie handling
> - Cancel requests using `AbortController`
> - Automatically inject tenant and organization headers
Example:
> Here are …
=> Fix ts config issue

apps/mobile/tsconfig.json
_A short and clear title that describes what this PR does._
Example:
> Add Retry, Cache, and Logging Features to API Service
Please describe **what you did**, and **why**.
- What problem or feature does this PR address?
- What changes were made?
- Why are these changes useful?
Example:
> This PR adds advanced features to the API request system:
>
> - Retry failed requests with exponential delay
> - Cache GET responses with TTL
> - Log all requests and responses
> - Allow cancelling requests
>
> These features improve reliability, performance, and debugging.
Example:
> Here are the major changes in that his PR adds
>
> - New `CookieManagement` class for cookie handling
> - Cancel requests using `AbortController`
> - Automatically inject tenant and organization headers
Example:
> Here are …
=> Fix tsconfig to clear types errors

apps/mobile/tsconfig.json
_A short and clear title that describes what this PR does._
Example:
> Add Retry, Cache, and Logging Features to API Service
Please describe **what you did**, and **why**.
- What problem or feature does this PR address?
- What changes were made?
- Why are these changes useful?
Example:
> This PR adds advanced features to the API request system:
>
> - Retry failed requests with exponential delay
> - Cache GET responses with TTL
> - Log all requests and responses
> - Allow cancelling requests
>
> These features improve reliability, performance, and debugging.
Example:
> Here are the major changes in that his PR adds
>
> - New `CookieManagement` class for cookie handling
> - Cancel requests using `AbortController`
> - Automatically inject tenant and organization headers
Example:
> Here are …
=> Release mobile app

apps/web/app/[locale]/(main)/kanban/page.tsx, apps/web/core/components/common/skeleton/kanban-view-skeleton.tsx, apps/web/core/components/pages/kanban/team-members-kanban-view.tsx
- Adjust ScrollArea width to full viewport width for better responsiveness
- Fix horizontal scrolling behavior for kanban columns
- Improve container structure with proper wrapper div
- Optimize padding and gap spacing between columns
- Ensure consistent layout across different screen sizes
_A short and clear title that describes what this PR does._
Example:
> Add Retry, Cache, and Logging Features to API Service
Please describe **what you did**, and **why**.
- What problem or feature does this PR address?
- What changes were made?
- Why are these changes useful?
Example:
> This PR adds advanced features to the API request system:
>
> - Retry failed requests with exponential delay
> - Cache GET responses with TTL
> - Log all requests and responses
> - Allow cancelling requests
>
> These …
=>  [Fix]: 3914-kanban-spacing-issues
